/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int right_arm_regressor(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int right_arm_regressor_alloc_mem(void);
int right_arm_regressor_init_mem(int mem);
void right_arm_regressor_free_mem(int mem);
int right_arm_regressor_checkout(void);
void right_arm_regressor_release(int mem);
void right_arm_regressor_incref(void);
void right_arm_regressor_decref(void);
casadi_int right_arm_regressor_n_in(void);
casadi_int right_arm_regressor_n_out(void);
casadi_real right_arm_regressor_default_in(casadi_int i);
const char* right_arm_regressor_name_in(casadi_int i);
const char* right_arm_regressor_name_out(casadi_int i);
const casadi_int* right_arm_regressor_sparsity_in(casadi_int i);
const casadi_int* right_arm_regressor_sparsity_out(casadi_int i);
int right_arm_regressor_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int right_arm_regressor_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define right_arm_regressor_SZ_ARG 4
#define right_arm_regressor_SZ_RES 1
#define right_arm_regressor_SZ_IW 0
#define right_arm_regressor_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
