/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) right_arm_params_to_X_base_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {45, 1, 1};

/* right_arm_params_to_X_base:(i0,i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24,i25,i26,i27,i28,i29,i30,i31,i32,i33,i34,i35,i36,i37,i38,i39,i40,i41,i42,i43,i44,i45,i46,i47,i48,i49,i50,i51,i52,i53,i54,i55,i56,i57,i58,i59,i60,i61,i62,i63,i64,i65,i66,i67,i68,i69)->(o0[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30;
  a00=arg[65]? arg[65][0] : 0;
  a01=arg[60]? arg[60][0] : 0;
  a02=arg[62]? arg[62][0] : 0;
  a03=arg[61]? arg[61][0] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a00=(a00-a04);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[66]? arg[66][0] : 0;
  a04=arg[63]? arg[63][0] : 0;
  a05=(a04*a03);
  a05=(a01*a05);
  a00=(a00-a05);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[58]? arg[58][0] : 0;
  a05=arg[50]? arg[50][0] : 0;
  a06=arg[53]? arg[53][0] : 0;
  a07=arg[52]? arg[52][0] : 0;
  a08=(a06*a07);
  a08=(a05*a08);
  a00=(a00-a08);
  a08=-4.9761602181756486e-06;
  a09=arg[64]? arg[64][0] : 0;
  a10=casadi_sq(a04);
  a11=casadi_sq(a02);
  a10=(a10+a11);
  a10=(a01*a10);
  a09=(a09+a10);
  a08=(a08*a09);
  a10=-1.2990691489295819e-05;
  a11=(a01*a04);
  a10=(a10*a11);
  a08=(a08+a10);
  a00=(a00+a08);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[55]? arg[55][0] : 0;
  a08=arg[51]? arg[51][0] : 0;
  a10=(a07*a08);
  a10=(a05*a10);
  a00=(a00-a10);
  a10=4.1366854091587609e-03;
  a10=(a10*a09);
  a12=1.0802046273123435e-02;
  a12=(a12*a11);
  a10=(a10+a12);
  a12=7.5067665666875145e-06;
  a12=(a12*a01);
  a10=(a10+a12);
  a00=(a00+a10);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[56]? arg[56][0] : 0;
  a10=(a06*a08);
  a10=(a05*a10);
  a00=(a00-a10);
  a10=1.2029118415024754e-03;
  a10=(a10*a09);
  a12=8.3617331302336149e-07;
  a12=(a12*a11);
  a10=(a10+a12);
  a00=(a00+a10);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[45]? arg[45][0] : 0;
  a10=arg[40]? arg[40][0] : 0;
  a12=arg[42]? arg[42][0] : 0;
  a13=arg[41]? arg[41][0] : 0;
  a14=(a12*a13);
  a14=(a10*a14);
  a00=(a00-a14);
  a14=1.1203111104734343e-02;
  a15=arg[54]? arg[54][0] : 0;
  a16=casadi_sq(a06);
  a17=casadi_sq(a07);
  a16=(a16+a17);
  a16=(a05*a16);
  a15=(a15+a16);
  a14=(a14*a15);
  a16=2.0792422482818566e-07;
  a16=(a16*a09);
  a14=(a14+a16);
  a16=-5.5899493951537928e-04;
  a17=(a10*a13);
  a16=(a16*a17);
  a14=(a14+a16);
  a16=1.0009666363493284e-06;
  a16=(a16*a11);
  a14=(a14+a16);
  a16=1.3061654111648079e-06;
  a16=(a16*a01);
  a14=(a14+a16);
  a00=(a00+a14);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[69]? arg[69][0] : 0;
  a14=casadi_sq(a02);
  a16=casadi_sq(a03);
  a14=(a14+a16);
  a14=(a01*a14);
  a00=(a00+a14);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[68]? arg[68][0] : 0;
  a14=(a04*a02);
  a14=(a01*a14);
  a00=(a00-a14);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[48]? arg[48][0] : 0;
  a14=arg[43]? arg[43][0] : 0;
  a16=(a14*a12);
  a16=(a10*a16);
  a00=(a00-a16);
  a16=1.4588985946329182e-05;
  a16=(a16*a15);
  a18=-7.3065680309120475e-07;
  a18=(a18*a17);
  a16=(a16+a18);
  a00=(a00+a16);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[35]? arg[35][0] : 0;
  a16=arg[30]? arg[30][0] : 0;
  a18=arg[32]? arg[32][0] : 0;
  a19=arg[31]? arg[31][0] : 0;
  a20=(a18*a19);
  a20=(a16*a20);
  a00=(a00-a20);
  a20=3.8284565115447962e-08;
  a20=(a20*a15);
  a21=3.0092902262712063e-04;
  a22=arg[44]? arg[44][0] : 0;
  a23=casadi_sq(a14);
  a24=casadi_sq(a12);
  a23=(a23+a24);
  a23=(a10*a23);
  a22=(a22+a23);
  a21=(a21*a22);
  a20=(a20+a21);
  a21=-4.3110375983161772e-04;
  a23=(a16*a19);
  a21=(a21*a23);
  a20=(a20+a21);
  a21=-1.4449699516313098e-05;
  a21=(a21*a01);
  a20=(a20+a21);
  a21=-1.4449703981221153e-05;
  a21=(a21*a05);
  a20=(a20+a21);
  a21=-1.4449799422934986e-05;
  a21=(a21*a10);
  a20=(a20+a21);
  a00=(a00+a20);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[46]? arg[46][0] : 0;
  a20=(a14*a13);
  a20=(a10*a20);
  a00=(a00-a20);
  a20=-1.3020606313037804e-03;
  a20=(a20*a15);
  a21=-2.4165604110758295e-08;
  a21=(a21*a09);
  a20=(a20+a21);
  a21=-2.4265976011135154e-07;
  a21=(a21*a17);
  a20=(a20+a21);
  a21=-1.1633547495463132e-07;
  a21=(a21*a11);
  a20=(a20+a21);
  a21=-1.5180663156018785e-07;
  a21=(a21*a01);
  a20=(a20+a21);
  a00=(a00+a20);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[67]? arg[67][0] : 0;
  a04=casadi_sq(a04);
  a20=casadi_sq(a03);
  a04=(a04+a20);
  a04=(a01*a04);
  a00=(a00+a04);
  a04=-1.0000000000000002e+00;
  a20=(a04*a09);
  a00=(a00+a20);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[38]? arg[38][0] : 0;
  a20=arg[33]? arg[33][0] : 0;
  a21=(a20*a18);
  a21=(a16*a21);
  a00=(a00-a21);
  a21=-3.2054446322116096e-07;
  a21=(a21*a22);
  a24=3.8896390212293559e-07;
  a24=(a24*a23);
  a21=(a21+a24);
  a24=8.5232919013683252e-08;
  a24=(a24*a01);
  a21=(a21+a24);
  a24=8.5232923764032127e-08;
  a24=(a24*a05);
  a21=(a21+a24);
  a24=8.5233025430137258e-08;
  a24=(a24*a10);
  a21=(a21+a24);
  a00=(a00+a21);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[57]? arg[57][0] : 0;
  a21=casadi_sq(a06);
  a24=casadi_sq(a08);
  a21=(a21+a24);
  a21=(a05*a21);
  a00=(a00+a21);
  a21=(a04*a15);
  a24=9.9996432800869894e-01;
  a24=(a24*a09);
  a21=(a21+a24);
  a24=1.3008756970255440e-03;
  a24=(a24*a11);
  a21=(a21+a24);
  a24=-1.1614106474804454e-04;
  a24=(a24*a01);
  a21=(a21+a24);
  a00=(a00+a21);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[36]? arg[36][0] : 0;
  a21=(a20*a19);
  a21=(a16*a21);
  a00=(a00-a21);
  a21=1.3551373516334980e-07;
  a21=(a21*a15);
  a24=1.0651816424420814e-03;
  a24=(a24*a22);
  a21=(a21+a24);
  a24=-2.3341180184433203e-04;
  a24=(a24*a23);
  a21=(a21+a24);
  a24=-5.1146793782837069e-05;
  a24=(a24*a01);
  a21=(a21+a24);
  a24=-5.1146809587024733e-05;
  a24=(a24*a05);
  a21=(a21+a24);
  a24=-5.1147147416709058e-05;
  a24=(a24*a10);
  a21=(a21+a24);
  a00=(a00+a21);
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[49]? arg[49][0] : 0;
  a21=casadi_sq(a12);
  a24=casadi_sq(a13);
  a21=(a21+a24);
  a21=(a10*a21);
  a00=(a00+a21);
  a21=9.9999830442239890e-01;
  a21=(a21*a15);
  a24=1.8559476058700246e-05;
  a24=(a24*a09);
  a21=(a21+a24);
  a24=3.6011112452703423e-04;
  a24=(a24*a17);
  a21=(a21+a24);
  a24=8.9347050992316499e-05;
  a24=(a24*a11);
  a21=(a21+a24);
  a24=1.1690648934316506e-04;
  a24=(a24*a01);
  a21=(a21+a24);
  a24=2.8243344529681546e-07;
  a24=(a24*a05);
  a21=(a21+a24);
  a00=(a00+a21);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[59]? arg[59][0] : 0;
  a21=casadi_sq(a07);
  a24=casadi_sq(a08);
  a21=(a21+a24);
  a21=(a05*a21);
  a00=(a00+a21);
  a21=9.9999855297624562e-01;
  a21=(a21*a09);
  a24=1.4795701020004083e-03;
  a24=(a24*a11);
  a21=(a21+a24);
  a24=1.1710744253872146e-04;
  a24=(a24*a01);
  a21=(a21+a24);
  a00=(a00+a21);
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[25]? arg[25][0] : 0;
  a21=arg[20]? arg[20][0] : 0;
  a24=arg[22]? arg[22][0] : 0;
  a25=arg[21]? arg[21][0] : 0;
  a26=(a24*a25);
  a26=(a21*a26);
  a00=(a00-a26);
  a26=8.4154909836034082e-03;
  a27=arg[29]? arg[29][0] : 0;
  a28=casadi_sq(a24);
  a29=casadi_sq(a25);
  a28=(a28+a29);
  a28=(a21*a28);
  a27=(a27+a28);
  a26=(a26*a27);
  a28=3.4417215794945658e-07;
  a28=(a28*a23);
  a26=(a26+a28);
  a28=3.2311084089571297e-04;
  a29=(a16*a20);
  a28=(a28*a29);
  a26=(a26+a28);
  a28=-2.7075161351980095e-08;
  a28=(a28*a01);
  a26=(a26+a28);
  a28=-2.7075161347556274e-08;
  a28=(a28*a05);
  a26=(a26+a28);
  a28=-2.7075161369951497e-08;
  a28=(a28*a10);
  a26=(a26+a28);
  a28=-1.0249304494586309e-07;
  a28=(a28*a16);
  a26=(a26+a28);
  a00=(a00+a26);
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[26]? arg[26][0] : 0;
  a26=arg[23]? arg[23][0] : 0;
  a28=(a26*a25);
  a28=(a21*a28);
  a00=(a00-a28);
  a28=-2.0092979311289345e-03;
  a28=(a28*a27);
  a30=6.5375586993451821e-07;
  a30=(a30*a29);
  a28=(a28+a30);
  a00=(a00+a28);
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[47]? arg[47][0] : 0;
  a28=casadi_sq(a14);
  a13=casadi_sq(a13);
  a28=(a28+a13);
  a28=(a10*a28);
  a00=(a00+a28);
  a28=9.9974725308648582e-01;
  a28=(a28*a15);
  a13=1.8554816669594186e-05;
  a13=(a13*a09);
  a28=(a28+a13);
  a04=(a04*a22);
  a28=(a28+a04);
  a04=3.8525781631193072e-04;
  a04=(a04*a17);
  a28=(a28+a04);
  a04=8.9324620257744567e-05;
  a04=(a04*a11);
  a28=(a28+a04);
  a04=1.1624289692068555e-04;
  a04=(a04*a01);
  a28=(a28+a04);
  a04=-3.5188030254980711e-07;
  a04=(a04*a05);
  a28=(a28+a04);
  a00=(a00+a28);
  if (res[0]!=0) res[0][19]=a00;
  a07=(a05*a07);
  a00=-4.1367237971150191e-03;
  a00=(a00*a11);
  a28=-1.0799270977403904e-02;
  a28=(a28*a01);
  a00=(a00+a28);
  a07=(a07+a00);
  if (res[0]!=0) res[0][20]=a07;
  a02=(a01*a02);
  if (res[0]!=0) res[0][21]=a02;
  a02=arg[15]? arg[15][0] : 0;
  a07=arg[10]? arg[10][0] : 0;
  a00=arg[12]? arg[12][0] : 0;
  a28=arg[11]? arg[11][0] : 0;
  a04=(a00*a28);
  a04=(a07*a04);
  a02=(a02-a04);
  a04=3.5678964074731137e-04;
  a13=arg[19]? arg[19][0] : 0;
  a09=casadi_sq(a00);
  a30=casadi_sq(a28);
  a09=(a09+a30);
  a09=(a07*a09);
  a13=(a13+a09);
  a04=(a04*a13);
  a09=8.5647669573064725e-04;
  a30=(a07*a28);
  a09=(a09*a30);
  a04=(a04+a09);
  a02=(a02+a04);
  if (res[0]!=0) res[0][22]=a02;
  a03=(a01*a03);
  if (res[0]!=0) res[0][23]=a03;
  a03=arg[39]? arg[39][0] : 0;
  a02=casadi_sq(a18);
  a04=casadi_sq(a19);
  a02=(a02+a04);
  a02=(a16*a02);
  a03=(a03+a02);
  a02=1.2722110121075878e-04;
  a02=(a02*a15);
  a04=9.9999886538667904e-01;
  a04=(a04*a22);
  a02=(a02+a04);
  a04=-1.2573331626455329e-05;
  a04=(a04*a17);
  a02=(a02+a04);
  a04=-4.3825695754610766e-01;
  a04=(a04*a23);
  a02=(a02+a04);
  a04=-4.8016824872811559e-02;
  a04=(a04*a01);
  a02=(a02+a04);
  a04=-4.8016839709877537e-02;
  a04=(a04*a05);
  a02=(a02+a04);
  a04=-4.8017156866391575e-02;
  a04=(a04*a10);
  a02=(a02+a04);
  a03=(a03+a02);
  if (res[0]!=0) res[0][24]=a03;
  a08=(a05*a08);
  a03=9.9999072020317881e-01;
  a03=(a03*a11);
  a02=6.9511790030939776e-04;
  a02=(a02*a01);
  a03=(a03+a02);
  a08=(a08+a03);
  if (res[0]!=0) res[0][25]=a08;
  a08=arg[28]? arg[28][0] : 0;
  a03=(a26*a24);
  a03=(a21*a03);
  a08=(a08-a03);
  a03=-1.6910426312340351e-05;
  a03=(a03*a27);
  a02=-6.4386184583296412e-07;
  a02=(a02*a29);
  a03=(a03+a02);
  a08=(a08+a03);
  if (res[0]!=0) res[0][26]=a08;
  a08=arg[34]? arg[34][0] : 0;
  a03=casadi_sq(a20);
  a02=casadi_sq(a18);
  a03=(a03+a02);
  a03=(a16*a03);
  a08=(a08+a03);
  a03=1.2251717090719856e-06;
  a03=(a03*a22);
  a02=1.0000040375641379e+00;
  a02=(a02*a27);
  a03=(a03+a02);
  a02=-9.0713168805588155e-07;
  a02=(a02*a23);
  a03=(a03+a02);
  a02=-6.4529382267528349e-04;
  a02=(a02*a29);
  a03=(a03+a02);
  a02=1.4309718007523730e-07;
  a02=(a02*a01);
  a03=(a03+a02);
  a02=1.4309716189100698e-07;
  a02=(a02*a05);
  a03=(a03+a02);
  a02=1.4309677332613868e-07;
  a02=(a02*a10);
  a03=(a03+a02);
  a02=2.0853207139132922e-07;
  a02=(a02*a16);
  a03=(a03+a02);
  a08=(a08+a03);
  if (res[0]!=0) res[0][27]=a08;
  a08=arg[37]? arg[37][0] : 0;
  a20=casadi_sq(a20);
  a19=casadi_sq(a19);
  a20=(a20+a19);
  a20=(a16*a20);
  a08=(a08+a20);
  a20=1.2722123403618687e-04;
  a20=(a20*a15);
  a15=9.9999990944161288e-01;
  a15=(a15*a22);
  a20=(a20+a15);
  a15=1.0000040375641381e+00;
  a15=(a15*a27);
  a20=(a20+a15);
  a15=-1.2573344753901166e-05;
  a15=(a15*a17);
  a20=(a20+a15);
  a15=-4.3825742512637178e-01;
  a15=(a15*a23);
  a20=(a20+a15);
  a15=-6.4529382267528273e-04;
  a15=(a15*a29);
  a20=(a20+a15);
  a15=-4.8016852143483287e-02;
  a15=(a15*a01);
  a20=(a20+a15);
  a15=-4.8016866980564746e-02;
  a15=(a15*a05);
  a20=(a20+a15);
  a15=-4.8017184137409907e-02;
  a15=(a15*a10);
  a20=(a20+a15);
  a15=2.0853207137832059e-07;
  a15=(a15*a16);
  a20=(a20+a15);
  a08=(a08+a20);
  if (res[0]!=0) res[0][28]=a08;
  a08=arg[14]? arg[14][0] : 0;
  a20=arg[13]? arg[13][0] : 0;
  a15=casadi_sq(a20);
  a22=casadi_sq(a00);
  a15=(a15+a22);
  a15=(a07*a15);
  a08=(a08+a15);
  a15=9.9999974540227221e-01;
  a15=(a15*a13);
  a22=-1.0000000000000004e+00;
  a19=arg[17]? arg[17][0] : 0;
  a03=casadi_sq(a20);
  a02=casadi_sq(a28);
  a03=(a03+a02);
  a03=(a07*a03);
  a19=(a19+a03);
  a22=(a22*a19);
  a15=(a15+a22);
  a22=-1.2223283613493337e-06;
  a22=(a22*a30);
  a15=(a15+a22);
  a22=1.4671052209924890e-06;
  a22=(a22*a01);
  a15=(a15+a22);
  a22=1.4671052209872993e-06;
  a22=(a22*a05);
  a15=(a15+a22);
  a22=1.4671052210122545e-06;
  a22=(a22*a10);
  a15=(a15+a22);
  a22=1.4671052209378023e-06;
  a22=(a22*a16);
  a15=(a15+a22);
  a22=1.4671052209310171e-06;
  a22=(a22*a21);
  a15=(a15+a22);
  a08=(a08+a15);
  if (res[0]!=0) res[0][29]=a08;
  a08=arg[18]? arg[18][0] : 0;
  a15=(a20*a00);
  a15=(a07*a15);
  a08=(a08-a15);
  a15=2.5662900447516031e-07;
  a15=(a15*a13);
  a22=5.5801271011278089e-07;
  a22=(a22*a30);
  a15=(a15+a22);
  a22=1.3929571013384106e-07;
  a22=(a22*a01);
  a15=(a15+a22);
  a22=1.3929571016361165e-07;
  a22=(a22*a05);
  a15=(a15+a22);
  a22=1.3929571016722348e-07;
  a22=(a22*a10);
  a15=(a15+a22);
  a22=1.3929571014591798e-07;
  a22=(a22*a16);
  a15=(a15+a22);
  a22=1.3929571014740402e-07;
  a22=(a22*a21);
  a15=(a15+a22);
  a08=(a08+a15);
  if (res[0]!=0) res[0][30]=a08;
  a06=(a05*a06);
  a08=1.0000636166928900e+00;
  a08=(a08*a17);
  a15=-1.2029230043836062e-03;
  a15=(a15*a11);
  a08=(a08+a15);
  a15=-1.8635408968644643e-04;
  a15=(a15*a01);
  a08=(a08+a15);
  a15=-1.8635408968648861e-04;
  a15=(a15*a05);
  a08=(a08+a15);
  a06=(a06+a08);
  if (res[0]!=0) res[0][31]=a06;
  a06=arg[16]? arg[16][0] : 0;
  a28=(a20*a28);
  a28=(a07*a28);
  a06=(a06-a28);
  a28=7.1927248549184808e-04;
  a28=(a28*a13);
  a08=-1.6263824061748158e-04;
  a08=(a08*a30);
  a28=(a28+a08);
  a06=(a06+a28);
  if (res[0]!=0) res[0][32]=a06;
  a12=(a10*a12);
  a06=1.1204536559831351e-02;
  a06=(a06*a17);
  a28=-5.6317069628943636e-04;
  a28=(a28*a01);
  a06=(a06+a28);
  a28=-5.6317069628944460e-04;
  a28=(a28*a05);
  a06=(a06+a28);
  a12=(a12+a06);
  if (res[0]!=0) res[0][33]=a12;
  a14=(a10*a14);
  a12=-1.3022263021562972e-03;
  a12=(a12*a17);
  a17=-1.0000006125864169e+00;
  a17=(a17*a23);
  a12=(a12+a17);
  a17=-2.1912826046050063e-01;
  a17=(a17*a01);
  a12=(a12+a17);
  a17=-2.1912826046050057e-01;
  a17=(a17*a05);
  a12=(a12+a17);
  a17=-2.1912850312026039e-01;
  a17=(a17*a10);
  a12=(a12+a17);
  a14=(a14+a12);
  if (res[0]!=0) res[0][34]=a14;
  a18=(a16*a18);
  a14=3.0092939131739821e-04;
  a14=(a14*a23);
  a12=-2.9921942649369977e-04;
  a12=(a12*a01);
  a14=(a14+a12);
  a12=-2.9921942649369538e-04;
  a12=(a12*a05);
  a14=(a14+a12);
  a12=-2.9921942649370850e-04;
  a12=(a12*a10);
  a14=(a14+a12);
  a18=(a18+a14);
  if (res[0]!=0) res[0][35]=a18;
  a18=arg[24]? arg[24][0] : 0;
  a14=casadi_sq(a26);
  a12=casadi_sq(a24);
  a14=(a14+a12);
  a14=(a21*a14);
  a18=(a18+a14);
  a14=-7.4863068885493099e-05;
  a14=(a14*a27);
  a12=1.0000005173529720e+00;
  a12=(a12*a13);
  a14=(a14+a12);
  a12=-5.4364377778204432e-06;
  a12=(a12*a29);
  a14=(a14+a12);
  a12=-4.5222946308213979e-01;
  a12=(a12*a30);
  a14=(a14+a12);
  a12=-5.1126862213068641e-02;
  a12=(a12*a01);
  a14=(a14+a12);
  a12=-5.1126862213068655e-02;
  a12=(a12*a05);
  a14=(a14+a12);
  a12=-5.1126862213068669e-02;
  a12=(a12*a10);
  a14=(a14+a12);
  a12=-5.1126860944139908e-02;
  a12=(a12*a16);
  a14=(a14+a12);
  a12=-5.1126967114016070e-02;
  a12=(a12*a21);
  a14=(a14+a12);
  a18=(a18+a14);
  if (res[0]!=0) res[0][36]=a18;
  a18=arg[27]? arg[27][0] : 0;
  a14=casadi_sq(a26);
  a12=casadi_sq(a25);
  a14=(a14+a12);
  a14=(a21*a14);
  a18=(a18+a14);
  a14=-9.9993321205939134e-01;
  a14=(a14*a27);
  a27=1.0000005173529727e+00;
  a27=(a27*a13);
  a14=(a14+a27);
  a27=5.4416485871323107e-06;
  a27=(a27*a29);
  a14=(a14+a27);
  a27=-4.5222946308213990e-01;
  a27=(a27*a30);
  a14=(a14+a27);
  a27=-5.1127072015431076e-02;
  a27=(a27*a01);
  a14=(a14+a27);
  a27=-5.1127072015431103e-02;
  a27=(a27*a05);
  a14=(a14+a27);
  a27=-5.1127072015431124e-02;
  a27=(a27*a10);
  a14=(a14+a27);
  a27=-5.1127073285576169e-02;
  a27=(a27*a16);
  a14=(a14+a27);
  a27=-5.1126967114016091e-02;
  a27=(a27*a21);
  a14=(a14+a27);
  a18=(a18+a14);
  if (res[0]!=0) res[0][37]=a18;
  a24=(a21*a24);
  a18=-8.9643368513606080e-06;
  a18=(a18*a23);
  a14=-8.4157720255405022e-03;
  a14=(a14*a29);
  a18=(a18+a14);
  a14=3.2389680698598856e-04;
  a14=(a14*a01);
  a18=(a18+a14);
  a14=3.2389680698591852e-04;
  a14=(a14*a05);
  a18=(a18+a14);
  a14=3.2389680698608359e-04;
  a14=(a14*a10);
  a18=(a18+a14);
  a14=3.2586114749835022e-04;
  a14=(a14*a16);
  a18=(a18+a14);
  a24=(a24+a18);
  if (res[0]!=0) res[0][38]=a24;
  a25=(a21*a25);
  a24=-1.0651430754567912e-03;
  a24=(a24*a23);
  a18=-9.9996256791610783e-01;
  a18=(a18*a29);
  a24=(a24+a18);
  a18=8.6512145844711336e-05;
  a18=(a18*a01);
  a24=(a24+a18);
  a18=8.6512145844701212e-05;
  a18=(a18*a05);
  a24=(a24+a18);
  a18=8.6512145844761982e-05;
  a18=(a18*a10);
  a24=(a24+a18);
  a18=3.1991521059895916e-04;
  a18=(a18*a16);
  a24=(a24+a18);
  a25=(a25+a24);
  if (res[0]!=0) res[0][39]=a25;
  a25=arg[9]? arg[9][0] : 0;
  a24=arg[0]? arg[0][0] : 0;
  a18=arg[2]? arg[2][0] : 0;
  a14=casadi_sq(a18);
  a27=arg[1]? arg[1][0] : 0;
  a12=casadi_sq(a27);
  a14=(a14+a12);
  a14=(a24*a14);
  a25=(a25+a14);
  a14=-9.9999886519462655e-01;
  a14=(a14*a13);
  a13=9.9999847514111129e-01;
  a13=(a13*a19);
  a14=(a14+a13);
  a13=1.3978886800611081e-05;
  a13=(a13*a30);
  a14=(a14+a13);
  a13=8.5690248825619588e-05;
  a13=(a13*a01);
  a14=(a14+a13);
  a13=8.5690248825598012e-05;
  a13=(a13*a05);
  a14=(a14+a13);
  a13=8.5690248825526103e-05;
  a13=(a13*a10);
  a14=(a14+a13);
  a13=-1.8259783830026879e-02;
  a20=(a07*a20);
  a13=(a13*a20);
  a14=(a14+a13);
  a13=8.5690248825659134e-05;
  a13=(a13*a16);
  a14=(a14+a13);
  a13=8.5690248825684301e-05;
  a13=(a13*a21);
  a14=(a14+a13);
  a13=8.3427618593782385e-05;
  a13=(a13*a07);
  a14=(a14+a13);
  a25=(a25+a14);
  if (res[0]!=0) res[0][40]=a25;
  a26=(a21*a26);
  a25=2.1403413685835953e-06;
  a25=(a25*a23);
  a23=2.0093650332131262e-03;
  a23=(a23*a29);
  a25=(a25+a23);
  a23=-1.0000003223259075e+00;
  a23=(a23*a30);
  a25=(a25+a23);
  a23=-2.2611388406675578e-01;
  a29=(a23*a01);
  a25=(a25+a29);
  a29=-2.2611388406675573e-01;
  a29=(a29*a05);
  a25=(a25+a29);
  a23=(a23*a10);
  a25=(a25+a23);
  a23=-2.2611435307626862e-01;
  a23=(a23*a16);
  a25=(a25+a23);
  a23=-2.2611435307626865e-01;
  a23=(a23*a21);
  a25=(a25+a23);
  a26=(a26+a25);
  if (res[0]!=0) res[0][41]=a26;
  a27=(a24*a27);
  a26=-7.1927201040973391e-04;
  a26=(a26*a30);
  a25=-9.2924756356423822e-03;
  a25=(a25*a01);
  a26=(a26+a25);
  a25=-9.2924756356422503e-03;
  a25=(a25*a05);
  a26=(a26+a25);
  a25=-9.2924756356422902e-03;
  a25=(a25*a10);
  a26=(a26+a25);
  a25=9.9999921219825494e-01;
  a25=(a25*a20);
  a26=(a26+a25);
  a25=-9.2924756356423787e-03;
  a25=(a25*a16);
  a26=(a26+a25);
  a25=-9.2924756356423614e-03;
  a25=(a25*a21);
  a26=(a26+a25);
  a25=-9.1298379627449758e-03;
  a25=(a25*a07);
  a26=(a26+a25);
  a27=(a27+a26);
  if (res[0]!=0) res[0][42]=a27;
  a00=(a07*a00);
  a27=-3.5678968616580553e-04;
  a27=(a27*a30);
  a26=8.5647691378784422e-04;
  a26=(a26*a01);
  a27=(a27+a26);
  a26=8.5647691378779760e-04;
  a26=(a26*a05);
  a27=(a27+a26);
  a26=8.5647691378776952e-04;
  a26=(a26*a10);
  a27=(a27+a26);
  a26=8.5647691378768864e-04;
  a26=(a26*a16);
  a27=(a27+a26);
  a26=8.5647691378768268e-04;
  a26=(a26*a21);
  a27=(a27+a26);
  a00=(a00+a27);
  if (res[0]!=0) res[0][43]=a00;
  a24=(a24*a18);
  a18=-1.6202639655158945e-07;
  a18=(a18*a30);
  a30=-2.7147238910785117e-04;
  a30=(a30*a01);
  a18=(a18+a30);
  a30=-2.7147238910772459e-04;
  a30=(a30*a05);
  a18=(a18+a30);
  a30=-2.7147238910772145e-04;
  a30=(a30*a10);
  a18=(a18+a30);
  a30=2.2526424831197258e-04;
  a30=(a30*a20);
  a18=(a18+a30);
  a30=-2.7147238910753876e-04;
  a30=(a30*a16);
  a18=(a18+a30);
  a30=-2.7147238910753794e-04;
  a30=(a30*a21);
  a18=(a18+a30);
  a30=-2.7143575262557389e-04;
  a30=(a30*a07);
  a18=(a18+a30);
  a24=(a24+a18);
  if (res[0]!=0) res[0][44]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_release(int mem) {
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_incref(void) {
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int right_arm_params_to_X_base_n_in(void) { return 70;}

CASADI_SYMBOL_EXPORT casadi_int right_arm_params_to_X_base_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real right_arm_params_to_X_base_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_arm_params_to_X_base_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    case 9: return "i9";
    case 10: return "i10";
    case 11: return "i11";
    case 12: return "i12";
    case 13: return "i13";
    case 14: return "i14";
    case 15: return "i15";
    case 16: return "i16";
    case 17: return "i17";
    case 18: return "i18";
    case 19: return "i19";
    case 20: return "i20";
    case 21: return "i21";
    case 22: return "i22";
    case 23: return "i23";
    case 24: return "i24";
    case 25: return "i25";
    case 26: return "i26";
    case 27: return "i27";
    case 28: return "i28";
    case 29: return "i29";
    case 30: return "i30";
    case 31: return "i31";
    case 32: return "i32";
    case 33: return "i33";
    case 34: return "i34";
    case 35: return "i35";
    case 36: return "i36";
    case 37: return "i37";
    case 38: return "i38";
    case 39: return "i39";
    case 40: return "i40";
    case 41: return "i41";
    case 42: return "i42";
    case 43: return "i43";
    case 44: return "i44";
    case 45: return "i45";
    case 46: return "i46";
    case 47: return "i47";
    case 48: return "i48";
    case 49: return "i49";
    case 50: return "i50";
    case 51: return "i51";
    case 52: return "i52";
    case 53: return "i53";
    case 54: return "i54";
    case 55: return "i55";
    case 56: return "i56";
    case 57: return "i57";
    case 58: return "i58";
    case 59: return "i59";
    case 60: return "i60";
    case 61: return "i61";
    case 62: return "i62";
    case 63: return "i63";
    case 64: return "i64";
    case 65: return "i65";
    case 66: return "i66";
    case 67: return "i67";
    case 68: return "i68";
    case 69: return "i69";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_arm_params_to_X_base_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_arm_params_to_X_base_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    case 17: return casadi_s0;
    case 18: return casadi_s0;
    case 19: return casadi_s0;
    case 20: return casadi_s0;
    case 21: return casadi_s0;
    case 22: return casadi_s0;
    case 23: return casadi_s0;
    case 24: return casadi_s0;
    case 25: return casadi_s0;
    case 26: return casadi_s0;
    case 27: return casadi_s0;
    case 28: return casadi_s0;
    case 29: return casadi_s0;
    case 30: return casadi_s0;
    case 31: return casadi_s0;
    case 32: return casadi_s0;
    case 33: return casadi_s0;
    case 34: return casadi_s0;
    case 35: return casadi_s0;
    case 36: return casadi_s0;
    case 37: return casadi_s0;
    case 38: return casadi_s0;
    case 39: return casadi_s0;
    case 40: return casadi_s0;
    case 41: return casadi_s0;
    case 42: return casadi_s0;
    case 43: return casadi_s0;
    case 44: return casadi_s0;
    case 45: return casadi_s0;
    case 46: return casadi_s0;
    case 47: return casadi_s0;
    case 48: return casadi_s0;
    case 49: return casadi_s0;
    case 50: return casadi_s0;
    case 51: return casadi_s0;
    case 52: return casadi_s0;
    case 53: return casadi_s0;
    case 54: return casadi_s0;
    case 55: return casadi_s0;
    case 56: return casadi_s0;
    case 57: return casadi_s0;
    case 58: return casadi_s0;
    case 59: return casadi_s0;
    case 60: return casadi_s0;
    case 61: return casadi_s0;
    case 62: return casadi_s0;
    case 63: return casadi_s0;
    case 64: return casadi_s0;
    case 65: return casadi_s0;
    case 66: return casadi_s0;
    case 67: return casadi_s0;
    case 68: return casadi_s0;
    case 69: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_arm_params_to_X_base_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
