/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) right_arm_params_to_X_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {70, 1, 1};

/* right_arm_params_to_X:(i0,i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24,i25,i26,i27,i28,i29,i30,i31,i32,i33,i34,i35,i36,i37,i38,i39,i40,i41,i42,i43,i44,i45,i46,i47,i48,i49,i50,i51,i52,i53,i54,i55,i56,i57,i58,i59,i60,i61,i62,i63,i64,i65,i66,i67,i68,i69)->(o0[70]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[1]? arg[1][0] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][1]=a2;
  a2=arg[2]? arg[2][0] : 0;
  a3=(a0*a2);
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[3]? arg[3][0] : 0;
  a4=(a0*a3);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[4]? arg[4][0] : 0;
  a5=casadi_sq(a3);
  a6=casadi_sq(a2);
  a5=(a5+a6);
  a5=(a0*a5);
  a4=(a4+a5);
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[5]? arg[5][0] : 0;
  a5=(a2*a1);
  a5=(a0*a5);
  a4=(a4-a5);
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[7]? arg[7][0] : 0;
  a5=casadi_sq(a3);
  a6=casadi_sq(a1);
  a5=(a5+a6);
  a5=(a0*a5);
  a4=(a4+a5);
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[6]? arg[6][0] : 0;
  a5=(a3*a1);
  a5=(a0*a5);
  a4=(a4-a5);
  if (res[0]!=0) res[0][7]=a4;
  a4=arg[8]? arg[8][0] : 0;
  a3=(a3*a2);
  a3=(a0*a3);
  a4=(a4-a3);
  if (res[0]!=0) res[0][8]=a4;
  a4=arg[9]? arg[9][0] : 0;
  a2=casadi_sq(a2);
  a1=casadi_sq(a1);
  a2=(a2+a1);
  a0=(a0*a2);
  a4=(a4+a0);
  if (res[0]!=0) res[0][9]=a4;
  a4=arg[10]? arg[10][0] : 0;
  if (res[0]!=0) res[0][10]=a4;
  a0=arg[11]? arg[11][0] : 0;
  a2=(a4*a0);
  if (res[0]!=0) res[0][11]=a2;
  a2=arg[12]? arg[12][0] : 0;
  a1=(a4*a2);
  if (res[0]!=0) res[0][12]=a1;
  a1=arg[13]? arg[13][0] : 0;
  a3=(a4*a1);
  if (res[0]!=0) res[0][13]=a3;
  a3=arg[14]? arg[14][0] : 0;
  a5=casadi_sq(a1);
  a6=casadi_sq(a2);
  a5=(a5+a6);
  a5=(a4*a5);
  a3=(a3+a5);
  if (res[0]!=0) res[0][14]=a3;
  a3=arg[15]? arg[15][0] : 0;
  a5=(a2*a0);
  a5=(a4*a5);
  a3=(a3-a5);
  if (res[0]!=0) res[0][15]=a3;
  a3=arg[17]? arg[17][0] : 0;
  a5=casadi_sq(a1);
  a6=casadi_sq(a0);
  a5=(a5+a6);
  a5=(a4*a5);
  a3=(a3+a5);
  if (res[0]!=0) res[0][16]=a3;
  a3=arg[16]? arg[16][0] : 0;
  a5=(a1*a0);
  a5=(a4*a5);
  a3=(a3-a5);
  if (res[0]!=0) res[0][17]=a3;
  a3=arg[18]? arg[18][0] : 0;
  a1=(a1*a2);
  a1=(a4*a1);
  a3=(a3-a1);
  if (res[0]!=0) res[0][18]=a3;
  a3=arg[19]? arg[19][0] : 0;
  a2=casadi_sq(a2);
  a0=casadi_sq(a0);
  a2=(a2+a0);
  a4=(a4*a2);
  a3=(a3+a4);
  if (res[0]!=0) res[0][19]=a3;
  a3=arg[20]? arg[20][0] : 0;
  if (res[0]!=0) res[0][20]=a3;
  a4=arg[21]? arg[21][0] : 0;
  a2=(a3*a4);
  if (res[0]!=0) res[0][21]=a2;
  a2=arg[22]? arg[22][0] : 0;
  a0=(a3*a2);
  if (res[0]!=0) res[0][22]=a0;
  a0=arg[23]? arg[23][0] : 0;
  a1=(a3*a0);
  if (res[0]!=0) res[0][23]=a1;
  a1=arg[24]? arg[24][0] : 0;
  a5=casadi_sq(a0);
  a6=casadi_sq(a2);
  a5=(a5+a6);
  a5=(a3*a5);
  a1=(a1+a5);
  if (res[0]!=0) res[0][24]=a1;
  a1=arg[25]? arg[25][0] : 0;
  a5=(a2*a4);
  a5=(a3*a5);
  a1=(a1-a5);
  if (res[0]!=0) res[0][25]=a1;
  a1=arg[27]? arg[27][0] : 0;
  a5=casadi_sq(a0);
  a6=casadi_sq(a4);
  a5=(a5+a6);
  a5=(a3*a5);
  a1=(a1+a5);
  if (res[0]!=0) res[0][26]=a1;
  a1=arg[26]? arg[26][0] : 0;
  a5=(a0*a4);
  a5=(a3*a5);
  a1=(a1-a5);
  if (res[0]!=0) res[0][27]=a1;
  a1=arg[28]? arg[28][0] : 0;
  a0=(a0*a2);
  a0=(a3*a0);
  a1=(a1-a0);
  if (res[0]!=0) res[0][28]=a1;
  a1=arg[29]? arg[29][0] : 0;
  a2=casadi_sq(a2);
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a3=(a3*a2);
  a1=(a1+a3);
  if (res[0]!=0) res[0][29]=a1;
  a1=arg[30]? arg[30][0] : 0;
  if (res[0]!=0) res[0][30]=a1;
  a3=arg[31]? arg[31][0] : 0;
  a2=(a1*a3);
  if (res[0]!=0) res[0][31]=a2;
  a2=arg[32]? arg[32][0] : 0;
  a4=(a1*a2);
  if (res[0]!=0) res[0][32]=a4;
  a4=arg[33]? arg[33][0] : 0;
  a0=(a1*a4);
  if (res[0]!=0) res[0][33]=a0;
  a0=arg[34]? arg[34][0] : 0;
  a5=casadi_sq(a4);
  a6=casadi_sq(a2);
  a5=(a5+a6);
  a5=(a1*a5);
  a0=(a0+a5);
  if (res[0]!=0) res[0][34]=a0;
  a0=arg[35]? arg[35][0] : 0;
  a5=(a2*a3);
  a5=(a1*a5);
  a0=(a0-a5);
  if (res[0]!=0) res[0][35]=a0;
  a0=arg[37]? arg[37][0] : 0;
  a5=casadi_sq(a4);
  a6=casadi_sq(a3);
  a5=(a5+a6);
  a5=(a1*a5);
  a0=(a0+a5);
  if (res[0]!=0) res[0][36]=a0;
  a0=arg[36]? arg[36][0] : 0;
  a5=(a4*a3);
  a5=(a1*a5);
  a0=(a0-a5);
  if (res[0]!=0) res[0][37]=a0;
  a0=arg[38]? arg[38][0] : 0;
  a4=(a4*a2);
  a4=(a1*a4);
  a0=(a0-a4);
  if (res[0]!=0) res[0][38]=a0;
  a0=arg[39]? arg[39][0] : 0;
  a2=casadi_sq(a2);
  a3=casadi_sq(a3);
  a2=(a2+a3);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][39]=a0;
  a0=arg[40]? arg[40][0] : 0;
  if (res[0]!=0) res[0][40]=a0;
  a1=arg[41]? arg[41][0] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][41]=a2;
  a2=arg[42]? arg[42][0] : 0;
  a3=(a0*a2);
  if (res[0]!=0) res[0][42]=a3;
  a3=arg[43]? arg[43][0] : 0;
  a4=(a0*a3);
  if (res[0]!=0) res[0][43]=a4;
  a4=arg[44]? arg[44][0] : 0;
  a5=casadi_sq(a3);
  a6=casadi_sq(a2);
  a5=(a5+a6);
  a5=(a0*a5);
  a4=(a4+a5);
  if (res[0]!=0) res[0][44]=a4;
  a4=arg[45]? arg[45][0] : 0;
  a5=(a2*a1);
  a5=(a0*a5);
  a4=(a4-a5);
  if (res[0]!=0) res[0][45]=a4;
  a4=arg[47]? arg[47][0] : 0;
  a5=casadi_sq(a3);
  a6=casadi_sq(a1);
  a5=(a5+a6);
  a5=(a0*a5);
  a4=(a4+a5);
  if (res[0]!=0) res[0][46]=a4;
  a4=arg[46]? arg[46][0] : 0;
  a5=(a3*a1);
  a5=(a0*a5);
  a4=(a4-a5);
  if (res[0]!=0) res[0][47]=a4;
  a4=arg[48]? arg[48][0] : 0;
  a3=(a3*a2);
  a3=(a0*a3);
  a4=(a4-a3);
  if (res[0]!=0) res[0][48]=a4;
  a4=arg[49]? arg[49][0] : 0;
  a2=casadi_sq(a2);
  a1=casadi_sq(a1);
  a2=(a2+a1);
  a0=(a0*a2);
  a4=(a4+a0);
  if (res[0]!=0) res[0][49]=a4;
  a4=arg[50]? arg[50][0] : 0;
  if (res[0]!=0) res[0][50]=a4;
  a0=arg[51]? arg[51][0] : 0;
  a2=(a4*a0);
  if (res[0]!=0) res[0][51]=a2;
  a2=arg[52]? arg[52][0] : 0;
  a1=(a4*a2);
  if (res[0]!=0) res[0][52]=a1;
  a1=arg[53]? arg[53][0] : 0;
  a3=(a4*a1);
  if (res[0]!=0) res[0][53]=a3;
  a3=arg[54]? arg[54][0] : 0;
  a5=casadi_sq(a1);
  a6=casadi_sq(a2);
  a5=(a5+a6);
  a5=(a4*a5);
  a3=(a3+a5);
  if (res[0]!=0) res[0][54]=a3;
  a3=arg[55]? arg[55][0] : 0;
  a5=(a2*a0);
  a5=(a4*a5);
  a3=(a3-a5);
  if (res[0]!=0) res[0][55]=a3;
  a3=arg[57]? arg[57][0] : 0;
  a5=casadi_sq(a1);
  a6=casadi_sq(a0);
  a5=(a5+a6);
  a5=(a4*a5);
  a3=(a3+a5);
  if (res[0]!=0) res[0][56]=a3;
  a3=arg[56]? arg[56][0] : 0;
  a5=(a1*a0);
  a5=(a4*a5);
  a3=(a3-a5);
  if (res[0]!=0) res[0][57]=a3;
  a3=arg[58]? arg[58][0] : 0;
  a1=(a1*a2);
  a1=(a4*a1);
  a3=(a3-a1);
  if (res[0]!=0) res[0][58]=a3;
  a3=arg[59]? arg[59][0] : 0;
  a2=casadi_sq(a2);
  a0=casadi_sq(a0);
  a2=(a2+a0);
  a4=(a4*a2);
  a3=(a3+a4);
  if (res[0]!=0) res[0][59]=a3;
  a3=arg[60]? arg[60][0] : 0;
  if (res[0]!=0) res[0][60]=a3;
  a4=arg[61]? arg[61][0] : 0;
  a2=(a3*a4);
  if (res[0]!=0) res[0][61]=a2;
  a2=arg[62]? arg[62][0] : 0;
  a0=(a3*a2);
  if (res[0]!=0) res[0][62]=a0;
  a0=arg[63]? arg[63][0] : 0;
  a1=(a3*a0);
  if (res[0]!=0) res[0][63]=a1;
  a1=arg[64]? arg[64][0] : 0;
  a5=casadi_sq(a0);
  a6=casadi_sq(a2);
  a5=(a5+a6);
  a5=(a3*a5);
  a1=(a1+a5);
  if (res[0]!=0) res[0][64]=a1;
  a1=arg[65]? arg[65][0] : 0;
  a5=(a2*a4);
  a5=(a3*a5);
  a1=(a1-a5);
  if (res[0]!=0) res[0][65]=a1;
  a1=arg[67]? arg[67][0] : 0;
  a5=casadi_sq(a0);
  a6=casadi_sq(a4);
  a5=(a5+a6);
  a5=(a3*a5);
  a1=(a1+a5);
  if (res[0]!=0) res[0][66]=a1;
  a1=arg[66]? arg[66][0] : 0;
  a5=(a0*a4);
  a5=(a3*a5);
  a1=(a1-a5);
  if (res[0]!=0) res[0][67]=a1;
  a1=arg[68]? arg[68][0] : 0;
  a0=(a0*a2);
  a0=(a3*a0);
  a1=(a1-a0);
  if (res[0]!=0) res[0][68]=a1;
  a1=arg[69]? arg[69][0] : 0;
  a2=casadi_sq(a2);
  a4=casadi_sq(a4);
  a2=(a2+a4);
  a3=(a3*a2);
  a1=(a1+a3);
  if (res[0]!=0) res[0][69]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_release(int mem) {
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_incref(void) {
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int right_arm_params_to_X_n_in(void) { return 70;}

CASADI_SYMBOL_EXPORT casadi_int right_arm_params_to_X_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real right_arm_params_to_X_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_arm_params_to_X_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    case 9: return "i9";
    case 10: return "i10";
    case 11: return "i11";
    case 12: return "i12";
    case 13: return "i13";
    case 14: return "i14";
    case 15: return "i15";
    case 16: return "i16";
    case 17: return "i17";
    case 18: return "i18";
    case 19: return "i19";
    case 20: return "i20";
    case 21: return "i21";
    case 22: return "i22";
    case 23: return "i23";
    case 24: return "i24";
    case 25: return "i25";
    case 26: return "i26";
    case 27: return "i27";
    case 28: return "i28";
    case 29: return "i29";
    case 30: return "i30";
    case 31: return "i31";
    case 32: return "i32";
    case 33: return "i33";
    case 34: return "i34";
    case 35: return "i35";
    case 36: return "i36";
    case 37: return "i37";
    case 38: return "i38";
    case 39: return "i39";
    case 40: return "i40";
    case 41: return "i41";
    case 42: return "i42";
    case 43: return "i43";
    case 44: return "i44";
    case 45: return "i45";
    case 46: return "i46";
    case 47: return "i47";
    case 48: return "i48";
    case 49: return "i49";
    case 50: return "i50";
    case 51: return "i51";
    case 52: return "i52";
    case 53: return "i53";
    case 54: return "i54";
    case 55: return "i55";
    case 56: return "i56";
    case 57: return "i57";
    case 58: return "i58";
    case 59: return "i59";
    case 60: return "i60";
    case 61: return "i61";
    case 62: return "i62";
    case 63: return "i63";
    case 64: return "i64";
    case 65: return "i65";
    case 66: return "i66";
    case 67: return "i67";
    case 68: return "i68";
    case 69: return "i69";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_arm_params_to_X_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_arm_params_to_X_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    case 17: return casadi_s0;
    case 18: return casadi_s0;
    case 19: return casadi_s0;
    case 20: return casadi_s0;
    case 21: return casadi_s0;
    case 22: return casadi_s0;
    case 23: return casadi_s0;
    case 24: return casadi_s0;
    case 25: return casadi_s0;
    case 26: return casadi_s0;
    case 27: return casadi_s0;
    case 28: return casadi_s0;
    case 29: return casadi_s0;
    case 30: return casadi_s0;
    case 31: return casadi_s0;
    case 32: return casadi_s0;
    case 33: return casadi_s0;
    case 34: return casadi_s0;
    case 35: return casadi_s0;
    case 36: return casadi_s0;
    case 37: return casadi_s0;
    case 38: return casadi_s0;
    case 39: return casadi_s0;
    case 40: return casadi_s0;
    case 41: return casadi_s0;
    case 42: return casadi_s0;
    case 43: return casadi_s0;
    case 44: return casadi_s0;
    case 45: return casadi_s0;
    case 46: return casadi_s0;
    case 47: return casadi_s0;
    case 48: return casadi_s0;
    case 49: return casadi_s0;
    case 50: return casadi_s0;
    case 51: return casadi_s0;
    case 52: return casadi_s0;
    case 53: return casadi_s0;
    case 54: return casadi_s0;
    case 55: return casadi_s0;
    case 56: return casadi_s0;
    case 57: return casadi_s0;
    case 58: return casadi_s0;
    case 59: return casadi_s0;
    case 60: return casadi_s0;
    case 61: return casadi_s0;
    case 62: return casadi_s0;
    case 63: return casadi_s0;
    case 64: return casadi_s0;
    case 65: return casadi_s0;
    case 66: return casadi_s0;
    case 67: return casadi_s0;
    case 68: return casadi_s0;
    case 69: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_arm_params_to_X_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
