/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) right_arm_params_to_X_base_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {45, 1, 1};

/* right_arm_params_to_X_base:(i0,i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24,i25,i26,i27,i28,i29,i30,i31,i32,i33,i34,i35,i36,i37,i38,i39,i40,i41,i42,i43,i44,i45,i46,i47,i48,i49,i50,i51,i52,i53,i54,i55,i56,i57,i58,i59,i60,i61,i62,i63,i64,i65,i66,i67,i68,i69)->(o0[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[66]? arg[66][0] : 0;
  a01=arg[60]? arg[60][0] : 0;
  a02=arg[63]? arg[63][0] : 0;
  a03=arg[61]? arg[61][0] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a00=(a00-a04);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[65]? arg[65][0] : 0;
  a04=arg[62]? arg[62][0] : 0;
  a05=(a04*a03);
  a05=(a01*a05);
  a00=(a00-a05);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[68]? arg[68][0] : 0;
  a05=(a02*a04);
  a05=(a01*a05);
  a00=(a00-a05);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[55]? arg[55][0] : 0;
  a05=arg[50]? arg[50][0] : 0;
  a06=arg[52]? arg[52][0] : 0;
  a07=arg[51]? arg[51][0] : 0;
  a08=(a06*a07);
  a08=(a05*a08);
  a00=(a00-a08);
  a08=-9.9999999999111269e-03;
  a09=(a01*a02);
  a08=(a08*a09);
  a00=(a00+a08);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[58]? arg[58][0] : 0;
  a08=arg[53]? arg[53][0] : 0;
  a10=(a08*a06);
  a10=(a05*a10);
  a00=(a00-a10);
  a10=4.2162051034006330e-06;
  a11=arg[49]? arg[49][0] : 0;
  a12=arg[40]? arg[40][0] : 0;
  a13=arg[42]? arg[42][0] : 0;
  a14=casadi_sq(a13);
  a15=arg[41]? arg[41][0] : 0;
  a16=casadi_sq(a15);
  a14=(a14+a16);
  a14=(a12*a14);
  a11=(a11+a14);
  a10=(a10*a11);
  a14=4.2162051034314845e-06;
  a16=arg[54]? arg[54][0] : 0;
  a17=casadi_sq(a08);
  a18=casadi_sq(a06);
  a17=(a17+a18);
  a17=(a05*a17);
  a16=(a16+a17);
  a14=(a14*a16);
  a10=(a10+a14);
  a00=(a00+a10);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[56]? arg[56][0] : 0;
  a10=(a08*a07);
  a10=(a05*a10);
  a00=(a00-a10);
  a10=-4.2162051019505333e-08;
  a10=(a10*a09);
  a00=(a00+a10);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[45]? arg[45][0] : 0;
  a10=(a13*a15);
  a10=(a12*a10);
  a00=(a00-a10);
  a10=-4.0972050440928158e-06;
  a10=(a10*a11);
  a00=(a00+a10);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[69]? arg[69][0] : 0;
  a10=casadi_sq(a04);
  a14=casadi_sq(a03);
  a10=(a10+a14);
  a10=(a01*a10);
  a00=(a00+a10);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[67]? arg[67][0] : 0;
  a10=casadi_sq(a02);
  a14=casadi_sq(a03);
  a10=(a10+a14);
  a10=(a01*a10);
  a00=(a00+a10);
  a10=1.0000000000000007e+00;
  a14=(a10*a11);
  a14=(a14+a16);
  a00=(a00+a14);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[48]? arg[48][0] : 0;
  a14=arg[43]? arg[43][0] : 0;
  a17=(a14*a13);
  a17=(a12*a17);
  a00=(a00-a17);
  a17=-2.9709464315836412e-08;
  a17=(a17*a11);
  a00=(a00+a17);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[46]? arg[46][0] : 0;
  a17=(a14*a15);
  a17=(a12*a17);
  a00=(a00-a17);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[35]? arg[35][0] : 0;
  a17=arg[30]? arg[30][0] : 0;
  a18=arg[32]? arg[32][0] : 0;
  a19=arg[31]? arg[31][0] : 0;
  a20=(a18*a19);
  a20=(a17*a20);
  a00=(a00-a20);
  a20=4.0972050440998521e-06;
  a21=arg[47]? arg[47][0] : 0;
  a22=casadi_sq(a14);
  a23=casadi_sq(a15);
  a22=(a22+a23);
  a22=(a12*a22);
  a21=(a21+a22);
  a20=(a20*a21);
  a22=-8.9974625630792413e-07;
  a23=(a17*a18);
  a22=(a22*a23);
  a20=(a20+a22);
  a22=-1.9758428418848045e-07;
  a24=(a22*a05);
  a20=(a20+a24);
  a24=-1.9758428419012168e-07;
  a24=(a24*a01);
  a20=(a20+a24);
  a22=(a22*a12);
  a20=(a20+a22);
  a00=(a00+a20);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[64]? arg[64][0] : 0;
  a02=casadi_sq(a02);
  a20=casadi_sq(a04);
  a02=(a02+a20);
  a02=(a01*a02);
  a00=(a00+a02);
  a02=1.0000000000000009e+00;
  a02=(a02*a11);
  a20=1.0000000000000002e+00;
  a22=(a20*a16);
  a02=(a02+a22);
  a00=(a00+a02);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[36]? arg[36][0] : 0;
  a02=arg[33]? arg[33][0] : 0;
  a22=(a02*a19);
  a22=(a17*a22);
  a00=(a00-a22);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[38]? arg[38][0] : 0;
  a22=(a02*a18);
  a22=(a17*a22);
  a00=(a00-a22);
  a22=2.9709464368171954e-08;
  a22=(a22*a21);
  a00=(a00+a22);
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[44]? arg[44][0] : 0;
  a22=casadi_sq(a14);
  a24=casadi_sq(a13);
  a22=(a22+a24);
  a22=(a12*a22);
  a00=(a00+a22);
  a22=-9.9999999996642575e-01;
  a22=(a22*a11);
  a22=(a22-a21);
  a00=(a00+a22);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[25]? arg[25][0] : 0;
  a22=arg[20]? arg[20][0] : 0;
  a24=arg[22]? arg[22][0] : 0;
  a25=arg[21]? arg[21][0] : 0;
  a26=(a24*a25);
  a26=(a22*a26);
  a00=(a00-a26);
  a26=4.0972050441218944e-06;
  a27=arg[37]? arg[37][0] : 0;
  a28=casadi_sq(a02);
  a29=casadi_sq(a19);
  a28=(a28+a29);
  a28=(a17*a28);
  a27=(a27+a28);
  a26=(a26*a27);
  a00=(a00+a26);
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[59]? arg[59][0] : 0;
  a26=casadi_sq(a06);
  a28=casadi_sq(a07);
  a26=(a26+a28);
  a26=(a05*a26);
  a00=(a00+a26);
  a26=-9.9999999998222378e-01;
  a26=(a26*a11);
  a28=-9.9999999998222344e-01;
  a28=(a28*a16);
  a26=(a26+a28);
  a28=1.0000000000000327e-04;
  a28=(a28*a01);
  a26=(a26+a28);
  a00=(a00+a26);
  if (res[0]!=0) res[0][17]=a00;
  a03=(a01*a03);
  if (res[0]!=0) res[0][18]=a03;
  a03=arg[26]? arg[26][0] : 0;
  a00=arg[23]? arg[23][0] : 0;
  a26=(a00*a25);
  a26=(a22*a26);
  a03=(a03-a26);
  if (res[0]!=0) res[0][19]=a03;
  a03=arg[28]? arg[28][0] : 0;
  a26=(a00*a24);
  a26=(a22*a26);
  a03=(a03-a26);
  a26=2.9709464507780199e-08;
  a26=(a26*a27);
  a03=(a03+a26);
  if (res[0]!=0) res[0][20]=a03;
  a04=(a01*a04);
  if (res[0]!=0) res[0][21]=a04;
  a04=arg[39]? arg[39][0] : 0;
  a03=casadi_sq(a18);
  a26=casadi_sq(a19);
  a03=(a03+a26);
  a03=(a17*a03);
  a04=(a04+a03);
  a03=9.9999999999999944e-01;
  a03=(a03*a21);
  a26=-4.3920001399999997e-01;
  a26=(a26*a23);
  a03=(a03+a26);
  a26=-4.8224163074400077e-02;
  a26=(a26*a05);
  a03=(a03+a26);
  a26=-4.8224163074400063e-02;
  a28=(a26*a01);
  a03=(a03+a28);
  a28=-4.8224163074400070e-02;
  a28=(a28*a12);
  a03=(a03+a28);
  a04=(a04+a03);
  if (res[0]!=0) res[0][22]=a04;
  a06=(a05*a06);
  a04=-9.9999999999111178e-01;
  a04=(a04*a09);
  a06=(a06+a04);
  if (res[0]!=0) res[0][23]=a06;
  a06=(a05*a07);
  a04=-1.0000000000000011e-02;
  a04=(a04*a01);
  a06=(a06+a04);
  if (res[0]!=0) res[0][24]=a06;
  a06=arg[57]? arg[57][0] : 0;
  a04=casadi_sq(a08);
  a07=casadi_sq(a07);
  a04=(a04+a07);
  a04=(a05*a04);
  a06=(a06+a04);
  a04=9.9999999998222366e-01;
  a04=(a04*a11);
  a11=9.9999999999994150e-05;
  a11=(a11*a01);
  a04=(a04+a11);
  a06=(a06+a04);
  if (res[0]!=0) res[0][25]=a06;
  a06=arg[15]? arg[15][0] : 0;
  a04=arg[10]? arg[10][0] : 0;
  a11=arg[12]? arg[12][0] : 0;
  a07=arg[11]? arg[11][0] : 0;
  a03=(a11*a07);
  a03=(a04*a03);
  a06=(a06-a03);
  a03=-4.0972050440607124e-06;
  a28=arg[19]? arg[19][0] : 0;
  a16=casadi_sq(a11);
  a29=casadi_sq(a07);
  a16=(a16+a29);
  a16=(a04*a16);
  a28=(a28+a16);
  a03=(a03*a28);
  a16=9.2064198974858758e-07;
  a29=(a22*a00);
  a16=(a16*a29);
  a03=(a03+a16);
  a16=-2.0686825878961098e-07;
  a16=(a16*a05);
  a03=(a03+a16);
  a16=-2.0686825878957776e-07;
  a16=(a16*a01);
  a03=(a03+a16);
  a16=-2.0686825879389495e-07;
  a16=(a16*a12);
  a03=(a03+a16);
  a16=-2.0686825878191250e-07;
  a16=(a16*a17);
  a03=(a03+a16);
  a16=-2.0686825878615423e-07;
  a16=(a16*a22);
  a03=(a03+a16);
  a06=(a06+a03);
  if (res[0]!=0) res[0][26]=a06;
  a06=arg[34]? arg[34][0] : 0;
  a03=casadi_sq(a02);
  a18=casadi_sq(a18);
  a03=(a03+a18);
  a03=(a17*a03);
  a06=(a06+a03);
  a03=9.9999999996642519e-01;
  a03=(a03*a21);
  a21=-9.9999999999999967e-01;
  a21=(a21*a27);
  a03=(a03+a21);
  a21=-4.3920001399999992e-01;
  a21=(a21*a23);
  a03=(a03+a21);
  a21=-4.8224163074400056e-02;
  a21=(a21*a05);
  a03=(a03+a21);
  a26=(a26*a01);
  a03=(a03+a26);
  a26=-4.8224163074400049e-02;
  a26=(a26*a12);
  a03=(a03+a26);
  a06=(a06+a03);
  if (res[0]!=0) res[0][27]=a06;
  a06=arg[24]? arg[24][0] : 0;
  a03=casadi_sq(a00);
  a26=casadi_sq(a24);
  a03=(a03+a26);
  a03=(a22*a03);
  a06=(a06+a03);
  a03=9.9999999998321387e-01;
  a03=(a03*a27);
  a20=(a20*a28);
  a03=(a03+a20);
  a20=-4.4940000799622826e-01;
  a20=(a20*a29);
  a03=(a03+a20);
  a20=5.0490091797600056e-02;
  a26=(a20*a05);
  a03=(a03+a26);
  a26=5.0490091797600181e-02;
  a26=(a26*a01);
  a03=(a03+a26);
  a26=5.0490091797600049e-02;
  a21=(a26*a12);
  a03=(a03+a21);
  a21=(a20*a17);
  a03=(a03+a21);
  a20=(a20*a22);
  a03=(a03+a20);
  a06=(a06+a03);
  if (res[0]!=0) res[0][28]=a06;
  a06=arg[16]? arg[16][0] : 0;
  a03=arg[13]? arg[13][0] : 0;
  a20=(a03*a07);
  a20=(a04*a20);
  a06=(a06-a20);
  if (res[0]!=0) res[0][29]=a06;
  a06=arg[29]? arg[29][0] : 0;
  a20=casadi_sq(a24);
  a21=casadi_sq(a25);
  a20=(a20+a21);
  a20=(a22*a20);
  a06=(a06+a20);
  a20=9.9999999999999956e-01;
  a20=(a20*a27);
  a06=(a06+a20);
  if (res[0]!=0) res[0][30]=a06;
  a13=(a12*a13);
  a06=4.2162051033570328e-06;
  a06=(a06*a09);
  a09=-9.9999999999160638e-01;
  a08=(a05*a08);
  a09=(a09*a08);
  a06=(a06+a09);
  a13=(a13+a06);
  if (res[0]!=0) res[0][31]=a13;
  a13=arg[18]? arg[18][0] : 0;
  a06=(a03*a11);
  a06=(a04*a06);
  a13=(a13-a06);
  a06=2.9709464421271718e-08;
  a06=(a06*a28);
  a13=(a13+a06);
  if (res[0]!=0) res[0][32]=a13;
  a15=(a12*a15);
  a13=4.0972050437882490e-06;
  a13=(a13*a08);
  a15=(a15+a13);
  if (res[0]!=0) res[0][33]=a15;
  a14=(a12*a14);
  a15=2.9709464685188222e-08;
  a15=(a15*a08);
  a08=-1.0000000000083935e+00;
  a08=(a08*a23);
  a15=(a15+a08);
  a08=-2.1960000700184340e-01;
  a08=(a08*a05);
  a15=(a15+a08);
  a08=-2.1960000700184337e-01;
  a08=(a08*a01);
  a15=(a15+a08);
  a08=-2.1960000700184332e-01;
  a08=(a08*a12);
  a15=(a15+a08);
  a14=(a14+a15);
  if (res[0]!=0) res[0][34]=a14;
  a19=(a17*a19);
  a14=4.0972050438162620e-06;
  a14=(a14*a23);
  a15=8.9974625630116788e-07;
  a15=(a15*a05);
  a14=(a14+a15);
  a15=8.9974625636201586e-07;
  a15=(a15*a01);
  a14=(a14+a15);
  a15=8.9974625632233237e-07;
  a15=(a15*a12);
  a14=(a14+a15);
  a19=(a19+a14);
  if (res[0]!=0) res[0][35]=a19;
  a19=arg[27]? arg[27][0] : 0;
  a00=casadi_sq(a00);
  a14=casadi_sq(a25);
  a00=(a00+a14);
  a00=(a22*a00);
  a19=(a19+a00);
  a10=(a10*a28);
  a00=-4.4940000799622831e-01;
  a00=(a00*a29);
  a10=(a10+a00);
  a00=5.0490091797600035e-02;
  a00=(a00*a05);
  a10=(a10+a00);
  a00=5.0490091797600133e-02;
  a00=(a00*a01);
  a10=(a10+a00);
  a00=5.0490091797600022e-02;
  a00=(a00*a12);
  a10=(a10+a00);
  a00=5.0490091797600042e-02;
  a00=(a00*a17);
  a10=(a10+a00);
  a26=(a26*a22);
  a10=(a10+a26);
  a19=(a19+a10);
  if (res[0]!=0) res[0][36]=a19;
  a19=arg[17]? arg[17][0] : 0;
  a10=casadi_sq(a03);
  a26=casadi_sq(a07);
  a10=(a10+a26);
  a10=(a04*a10);
  a19=(a19+a10);
  a10=9.9999999996642597e-01;
  a10=(a10*a28);
  a26=-9.9999999999999922e-01;
  a00=arg[14]? arg[14][0] : 0;
  a14=casadi_sq(a03);
  a15=casadi_sq(a11);
  a14=(a14+a15);
  a14=(a04*a14);
  a00=(a00+a14);
  a26=(a26*a00);
  a10=(a10+a26);
  a19=(a19+a10);
  if (res[0]!=0) res[0][37]=a19;
  a25=(a22*a25);
  a19=4.0972050441569234e-06;
  a24=(a22*a24);
  a19=(a19*a24);
  a25=(a25+a19);
  if (res[0]!=0) res[0][38]=a25;
  a02=(a17*a02);
  a25=2.9709464218088548e-08;
  a25=(a25*a23);
  a23=-1.0000000000083940e+00;
  a23=(a23*a24);
  a25=(a25+a23);
  a02=(a02+a25);
  if (res[0]!=0) res[0][39]=a02;
  a07=(a04*a07);
  a02=-4.0972050440757260e-06;
  a02=(a02*a29);
  a07=(a07+a02);
  if (res[0]!=0) res[0][40]=a07;
  a07=arg[9]? arg[9][0] : 0;
  a02=arg[0]? arg[0][0] : 0;
  a25=arg[2]? arg[2][0] : 0;
  a23=casadi_sq(a25);
  a19=arg[1]? arg[1][0] : 0;
  a10=casadi_sq(a19);
  a23=(a23+a10);
  a23=(a02*a23);
  a07=(a07+a23);
  a23=-9.9999999998287004e-01;
  a23=(a23*a28);
  a28=9.9999999999965561e-01;
  a28=(a28*a00);
  a23=(a23+a28);
  a28=8.1000000847545968e-05;
  a28=(a28*a05);
  a23=(a23+a28);
  a28=8.1000000847481770e-05;
  a28=(a28*a01);
  a23=(a23+a28);
  a28=-1.7999999999778419e-02;
  a03=(a04*a03);
  a28=(a28*a03);
  a23=(a23+a28);
  a28=8.1000000847566975e-05;
  a28=(a28*a12);
  a23=(a23+a28);
  a28=8.1000000847559968e-05;
  a28=(a28*a17);
  a23=(a23+a28);
  a28=8.1000000847530790e-05;
  a28=(a28*a22);
  a23=(a23+a28);
  a28=8.0999999999999177e-05;
  a28=(a28*a04);
  a23=(a23+a28);
  a07=(a07+a23);
  if (res[0]!=0) res[0][41]=a07;
  a11=(a04*a11);
  a07=2.9709464483200788e-08;
  a07=(a07*a24);
  a24=9.9999999999160638e-01;
  a24=(a24*a29);
  a07=(a07+a24);
  a24=-2.2470000400000029e-01;
  a23=(a24*a05);
  a07=(a07+a23);
  a24=(a24*a01);
  a07=(a07+a24);
  a24=-2.2470000400000034e-01;
  a24=(a24*a12);
  a07=(a07+a24);
  a24=-2.2470000400000004e-01;
  a24=(a24*a17);
  a07=(a07+a24);
  a24=-2.2470000399999998e-01;
  a24=(a24*a22);
  a07=(a07+a24);
  a11=(a11+a07);
  if (res[0]!=0) res[0][42]=a11;
  a25=(a02*a25);
  a11=-2.9709464828267532e-08;
  a11=(a11*a29);
  a29=9.0000000000001936e-03;
  a29=(a29*a05);
  a11=(a11+a29);
  a29=9.0000000000001086e-03;
  a29=(a29*a01);
  a11=(a11+a29);
  a29=-9.9999999998768718e-01;
  a29=(a29*a03);
  a11=(a11+a29);
  a29=9.0000000000001520e-03;
  a29=(a29*a12);
  a11=(a11+a29);
  a29=9.0000000000000288e-03;
  a29=(a29*a17);
  a11=(a11+a29);
  a29=9.0000000000000548e-03;
  a29=(a29*a22);
  a11=(a11+a29);
  a29=9.0000000000000045e-03;
  a29=(a29*a04);
  a11=(a11+a29);
  a25=(a25+a11);
  if (res[0]!=0) res[0][43]=a25;
  a02=(a02*a19);
  a19=4.9277312620873786e-06;
  a19=(a19*a03);
  a02=(a02+a19);
  if (res[0]!=0) res[0][44]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_release(int mem) {
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_incref(void) {
}

CASADI_SYMBOL_EXPORT void right_arm_params_to_X_base_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int right_arm_params_to_X_base_n_in(void) { return 70;}

CASADI_SYMBOL_EXPORT casadi_int right_arm_params_to_X_base_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real right_arm_params_to_X_base_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_arm_params_to_X_base_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    case 9: return "i9";
    case 10: return "i10";
    case 11: return "i11";
    case 12: return "i12";
    case 13: return "i13";
    case 14: return "i14";
    case 15: return "i15";
    case 16: return "i16";
    case 17: return "i17";
    case 18: return "i18";
    case 19: return "i19";
    case 20: return "i20";
    case 21: return "i21";
    case 22: return "i22";
    case 23: return "i23";
    case 24: return "i24";
    case 25: return "i25";
    case 26: return "i26";
    case 27: return "i27";
    case 28: return "i28";
    case 29: return "i29";
    case 30: return "i30";
    case 31: return "i31";
    case 32: return "i32";
    case 33: return "i33";
    case 34: return "i34";
    case 35: return "i35";
    case 36: return "i36";
    case 37: return "i37";
    case 38: return "i38";
    case 39: return "i39";
    case 40: return "i40";
    case 41: return "i41";
    case 42: return "i42";
    case 43: return "i43";
    case 44: return "i44";
    case 45: return "i45";
    case 46: return "i46";
    case 47: return "i47";
    case 48: return "i48";
    case 49: return "i49";
    case 50: return "i50";
    case 51: return "i51";
    case 52: return "i52";
    case 53: return "i53";
    case 54: return "i54";
    case 55: return "i55";
    case 56: return "i56";
    case 57: return "i57";
    case 58: return "i58";
    case 59: return "i59";
    case 60: return "i60";
    case 61: return "i61";
    case 62: return "i62";
    case 63: return "i63";
    case 64: return "i64";
    case 65: return "i65";
    case 66: return "i66";
    case 67: return "i67";
    case 68: return "i68";
    case 69: return "i69";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* right_arm_params_to_X_base_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_arm_params_to_X_base_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    case 17: return casadi_s0;
    case 18: return casadi_s0;
    case 19: return casadi_s0;
    case 20: return casadi_s0;
    case 21: return casadi_s0;
    case 22: return casadi_s0;
    case 23: return casadi_s0;
    case 24: return casadi_s0;
    case 25: return casadi_s0;
    case 26: return casadi_s0;
    case 27: return casadi_s0;
    case 28: return casadi_s0;
    case 29: return casadi_s0;
    case 30: return casadi_s0;
    case 31: return casadi_s0;
    case 32: return casadi_s0;
    case 33: return casadi_s0;
    case 34: return casadi_s0;
    case 35: return casadi_s0;
    case 36: return casadi_s0;
    case 37: return casadi_s0;
    case 38: return casadi_s0;
    case 39: return casadi_s0;
    case 40: return casadi_s0;
    case 41: return casadi_s0;
    case 42: return casadi_s0;
    case 43: return casadi_s0;
    case 44: return casadi_s0;
    case 45: return casadi_s0;
    case 46: return casadi_s0;
    case 47: return casadi_s0;
    case 48: return casadi_s0;
    case 49: return casadi_s0;
    case 50: return casadi_s0;
    case 51: return casadi_s0;
    case 52: return casadi_s0;
    case 53: return casadi_s0;
    case 54: return casadi_s0;
    case 55: return casadi_s0;
    case 56: return casadi_s0;
    case 57: return casadi_s0;
    case 58: return casadi_s0;
    case 59: return casadi_s0;
    case 60: return casadi_s0;
    case 61: return casadi_s0;
    case 62: return casadi_s0;
    case 63: return casadi_s0;
    case 64: return casadi_s0;
    case 65: return casadi_s0;
    case 66: return casadi_s0;
    case 67: return casadi_s0;
    case 68: return casadi_s0;
    case 69: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* right_arm_params_to_X_base_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int right_arm_params_to_X_base_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
