/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) left_arm_params_to_X_base_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {45, 1, 1};

/* left_arm_params_to_X_base:(i0,i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24,i25,i26,i27,i28,i29,i30,i31,i32,i33,i34,i35,i36,i37,i38,i39,i40,i41,i42,i43,i44,i45,i46,i47,i48,i49,i50,i51,i52,i53,i54,i55,i56,i57,i58,i59,i60,i61,i62,i63,i64,i65,i66,i67,i68,i69)->(o0[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=arg[68]? arg[68][0] : 0;
  a01=arg[60]? arg[60][0] : 0;
  a02=arg[63]? arg[63][0] : 0;
  a03=arg[62]? arg[62][0] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a00=(a00-a04);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[65]? arg[65][0] : 0;
  a04=arg[61]? arg[61][0] : 0;
  a05=(a03*a04);
  a05=(a01*a05);
  a00=(a00-a05);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[55]? arg[55][0] : 0;
  a05=arg[50]? arg[50][0] : 0;
  a06=arg[52]? arg[52][0] : 0;
  a07=arg[51]? arg[51][0] : 0;
  a08=(a06*a07);
  a08=(a05*a08);
  a00=(a00-a08);
  a08=-1.0000000000000045e-02;
  a09=(a05*a06);
  a08=(a08*a09);
  a00=(a00+a08);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[66]? arg[66][0] : 0;
  a08=(a02*a04);
  a08=(a01*a08);
  a00=(a00-a08);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[56]? arg[56][0] : 0;
  a08=arg[53]? arg[53][0] : 0;
  a10=(a08*a07);
  a10=(a05*a10);
  a00=(a00-a10);
  a10=-4.2162051059591313e-08;
  a10=(a10*a09);
  a00=(a00+a10);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[58]? arg[58][0] : 0;
  a10=(a08*a06);
  a10=(a05*a10);
  a00=(a00-a10);
  a10=-4.2162051034163937e-06;
  a11=arg[67]? arg[67][0] : 0;
  a12=casadi_sq(a02);
  a13=casadi_sq(a04);
  a12=(a12+a13);
  a12=(a01*a12);
  a11=(a11+a12);
  a10=(a10*a11);
  a00=(a00+a10);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[45]? arg[45][0] : 0;
  a10=arg[40]? arg[40][0] : 0;
  a12=arg[42]? arg[42][0] : 0;
  a13=arg[41]? arg[41][0] : 0;
  a14=(a12*a13);
  a14=(a10*a14);
  a00=(a00-a14);
  a14=4.0972050438302406e-06;
  a15=arg[57]? arg[57][0] : 0;
  a16=casadi_sq(a08);
  a17=casadi_sq(a07);
  a16=(a16+a17);
  a16=(a05*a16);
  a15=(a15+a16);
  a14=(a14*a15);
  a00=(a00+a14);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[46]? arg[46][0] : 0;
  a14=arg[43]? arg[43][0] : 0;
  a16=(a14*a13);
  a16=(a10*a16);
  a00=(a00-a16);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[64]? arg[64][0] : 0;
  a16=casadi_sq(a02);
  a17=casadi_sq(a03);
  a16=(a16+a17);
  a16=(a01*a16);
  a00=(a00+a16);
  a16=-1.0000000000000002e+00;
  a17=(a16*a11);
  a00=(a00+a17);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[69]? arg[69][0] : 0;
  a17=casadi_sq(a03);
  a18=casadi_sq(a04);
  a17=(a17+a18);
  a17=(a01*a17);
  a00=(a00+a17);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[35]? arg[35][0] : 0;
  a17=arg[30]? arg[30][0] : 0;
  a18=arg[32]? arg[32][0] : 0;
  a19=arg[31]? arg[31][0] : 0;
  a20=(a18*a19);
  a20=(a17*a20);
  a00=(a00-a20);
  a20=4.0972050440320920e-06;
  a21=arg[47]? arg[47][0] : 0;
  a22=casadi_sq(a14);
  a23=casadi_sq(a13);
  a22=(a22+a23);
  a22=(a10*a22);
  a21=(a21+a22);
  a20=(a20*a21);
  a22=-8.9974625637224188e-07;
  a23=(a10*a14);
  a22=(a22*a23);
  a20=(a20+a22);
  a00=(a00+a20);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[59]? arg[59][0] : 0;
  a20=casadi_sq(a06);
  a22=casadi_sq(a07);
  a20=(a20+a22);
  a20=(a05*a20);
  a00=(a00+a20);
  a20=9.9999999998222389e-01;
  a20=(a20*a11);
  a22=1.0000000000000800e-04;
  a22=(a22*a01);
  a20=(a20+a22);
  a00=(a00+a20);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[48]? arg[48][0] : 0;
  a20=(a14*a12);
  a20=(a10*a20);
  a00=(a00-a20);
  a20=2.9709464842219554e-08;
  a20=(a20*a15);
  a00=(a00+a20);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[54]? arg[54][0] : 0;
  a20=casadi_sq(a08);
  a06=casadi_sq(a06);
  a20=(a20+a06);
  a20=(a05*a20);
  a00=(a00+a20);
  a20=9.9999999998222366e-01;
  a20=(a20*a11);
  a11=-1.0000000000000009e+00;
  a11=(a11*a15);
  a20=(a20+a11);
  a11=-1.0000000000000671e-04;
  a11=(a11*a01);
  a20=(a20+a11);
  a00=(a00+a20);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[38]? arg[38][0] : 0;
  a20=arg[33]? arg[33][0] : 0;
  a11=(a20*a18);
  a11=(a17*a11);
  a00=(a00-a11);
  a11=2.9709464389536983e-08;
  a11=(a11*a21);
  a00=(a00+a11);
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[36]? arg[36][0] : 0;
  a11=(a20*a19);
  a11=(a17*a11);
  a00=(a00-a11);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[44]? arg[44][0] : 0;
  a14=casadi_sq(a14);
  a11=casadi_sq(a12);
  a14=(a14+a11);
  a14=(a10*a14);
  a00=(a00+a14);
  a14=9.9999999996642597e-01;
  a14=(a14*a15);
  a16=(a16*a21);
  a14=(a14+a16);
  a16=9.9999999996653262e-05;
  a16=(a16*a01);
  a14=(a14+a16);
  a00=(a00+a14);
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[25]? arg[25][0] : 0;
  a14=arg[20]? arg[20][0] : 0;
  a16=arg[22]? arg[22][0] : 0;
  a11=arg[21]? arg[21][0] : 0;
  a06=(a16*a11);
  a06=(a14*a06);
  a00=(a00-a06);
  a06=4.0972050440033776e-06;
  a06=(a06*a21);
  a22=4.0972050439626022e-06;
  a24=arg[34]? arg[34][0] : 0;
  a25=casadi_sq(a20);
  a26=casadi_sq(a18);
  a25=(a25+a26);
  a25=(a17*a25);
  a24=(a24+a25);
  a22=(a22*a24);
  a06=(a06+a22);
  a22=-1.7994925126192660e-06;
  a22=(a22*a23);
  a06=(a06+a22);
  a22=1.9758428418817967e-07;
  a22=(a22*a05);
  a06=(a06+a22);
  a22=1.9758428419175661e-07;
  a22=(a22*a01);
  a06=(a06+a22);
  a22=1.9758428417878033e-07;
  a22=(a22*a10);
  a06=(a06+a22);
  a00=(a00+a06);
  if (res[0]!=0) res[0][17]=a00;
  a03=(a01*a03);
  if (res[0]!=0) res[0][18]=a03;
  a04=(a01*a04);
  if (res[0]!=0) res[0][19]=a04;
  a04=arg[39]? arg[39][0] : 0;
  a03=casadi_sq(a18);
  a00=casadi_sq(a19);
  a03=(a03+a00);
  a03=(a17*a03);
  a04=(a04+a03);
  a03=9.9999999999999933e-01;
  a00=(a03*a21);
  a06=-4.3920001399631353e-01;
  a06=(a06*a23);
  a00=(a00+a06);
  a06=4.8224163074400084e-02;
  a06=(a06*a05);
  a00=(a00+a06);
  a06=4.8224163074401770e-02;
  a06=(a06*a01);
  a00=(a00+a06);
  a06=4.8224163074400070e-02;
  a06=(a06*a10);
  a00=(a00+a06);
  a04=(a04+a00);
  if (res[0]!=0) res[0][20]=a04;
  a04=arg[49]? arg[49][0] : 0;
  a00=casadi_sq(a12);
  a06=casadi_sq(a13);
  a00=(a00+a06);
  a00=(a10*a00);
  a04=(a04+a00);
  a00=1.0000000000000004e+00;
  a00=(a00*a15);
  a15=9.9999999999996291e-05;
  a15=(a15*a01);
  a00=(a00+a15);
  a04=(a04+a00);
  if (res[0]!=0) res[0][21]=a04;
  a04=arg[26]? arg[26][0] : 0;
  a00=arg[23]? arg[23][0] : 0;
  a15=(a00*a11);
  a15=(a14*a15);
  a04=(a04-a15);
  if (res[0]!=0) res[0][22]=a04;
  a07=(a05*a07);
  a04=-1.0000000000000002e-02;
  a04=(a04*a01);
  a07=(a07+a04);
  if (res[0]!=0) res[0][23]=a07;
  a02=(a01*a02);
  a07=-1.0000000000088884e+00;
  a07=(a07*a09);
  a02=(a02+a07);
  if (res[0]!=0) res[0][24]=a02;
  a02=arg[28]? arg[28][0] : 0;
  a07=(a00*a16);
  a07=(a14*a07);
  a02=(a02-a07);
  a07=2.9709464827603805e-08;
  a07=(a07*a21);
  a04=2.9709464448237898e-08;
  a04=(a04*a24);
  a07=(a07+a04);
  a02=(a02+a07);
  if (res[0]!=0) res[0][25]=a02;
  a02=arg[37]? arg[37][0] : 0;
  a07=casadi_sq(a20);
  a04=casadi_sq(a19);
  a07=(a07+a04);
  a07=(a17*a07);
  a02=(a02+a07);
  a07=-9.9999999996642563e-01;
  a07=(a07*a21);
  a07=(a07-a24);
  a04=4.3920001399631364e-01;
  a04=(a04*a23);
  a07=(a07+a04);
  a04=-4.8224163074400077e-02;
  a04=(a04*a05);
  a07=(a07+a04);
  a04=-4.8224163074401749e-02;
  a04=(a04*a01);
  a07=(a07+a04);
  a04=-4.8224163074400056e-02;
  a04=(a04*a10);
  a07=(a07+a04);
  a02=(a02+a07);
  if (res[0]!=0) res[0][26]=a02;
  a02=arg[15]? arg[15][0] : 0;
  a07=arg[10]? arg[10][0] : 0;
  a04=arg[12]? arg[12][0] : 0;
  a15=arg[11]? arg[11][0] : 0;
  a06=(a04*a15);
  a06=(a07*a06);
  a02=(a02-a06);
  a06=-4.0972050439704864e-06;
  a22=arg[19]? arg[19][0] : 0;
  a25=casadi_sq(a04);
  a26=casadi_sq(a15);
  a25=(a25+a26);
  a25=(a07*a25);
  a22=(a22+a25);
  a06=(a06*a22);
  a25=-9.2064198978290904e-07;
  a26=(a07*a04);
  a25=(a25*a26);
  a06=(a06+a25);
  a02=(a02+a06);
  if (res[0]!=0) res[0][27]=a02;
  a02=arg[29]? arg[29][0] : 0;
  a06=casadi_sq(a16);
  a25=casadi_sq(a11);
  a06=(a06+a25);
  a06=(a14*a06);
  a02=(a02+a06);
  a06=9.9999999998321276e-01;
  a06=(a06*a21);
  a03=(a03*a24);
  a06=(a06+a03);
  a03=-4.3920001399631342e-01;
  a03=(a03*a23);
  a06=(a06+a03);
  a03=4.8224163074400049e-02;
  a03=(a03*a05);
  a06=(a06+a03);
  a03=4.8224163074401714e-02;
  a03=(a03*a01);
  a06=(a06+a03);
  a03=4.8224163074400035e-02;
  a03=(a03*a10);
  a06=(a06+a03);
  a02=(a02+a06);
  if (res[0]!=0) res[0][28]=a02;
  a02=arg[27]? arg[27][0] : 0;
  a06=casadi_sq(a00);
  a03=casadi_sq(a11);
  a06=(a06+a03);
  a06=(a14*a06);
  a02=(a02+a06);
  a06=9.9999999999999900e-01;
  a06=(a06*a22);
  a03=4.4940000800000013e-01;
  a25=(a03*a26);
  a06=(a06+a25);
  a25=-5.0490091796790523e-02;
  a25=(a25*a05);
  a06=(a06+a25);
  a25=-5.0490091796790607e-02;
  a25=(a25*a01);
  a06=(a06+a25);
  a25=-5.0490091796790544e-02;
  a25=(a25*a10);
  a06=(a06+a25);
  a25=-5.0490091797600077e-02;
  a25=(a25*a14);
  a06=(a06+a25);
  a25=-5.0490091797600126e-02;
  a25=(a25*a17);
  a06=(a06+a25);
  a02=(a02+a06);
  if (res[0]!=0) res[0][29]=a02;
  a12=(a10*a12);
  a02=4.2162051036665115e-06;
  a02=(a02*a09);
  a09=-9.9999999999160627e-01;
  a08=(a05*a08);
  a09=(a09*a08);
  a02=(a02+a09);
  a12=(a12+a02);
  if (res[0]!=0) res[0][30]=a12;
  a13=(a10*a13);
  a12=4.0972050441100800e-06;
  a12=(a12*a08);
  a13=(a13+a12);
  if (res[0]!=0) res[0][31]=a13;
  a19=(a17*a19);
  a13=4.0972050441916111e-06;
  a13=(a13*a23);
  a19=(a19+a13);
  if (res[0]!=0) res[0][32]=a19;
  a19=arg[18]? arg[18][0] : 0;
  a13=arg[13]? arg[13][0] : 0;
  a12=(a13*a04);
  a12=(a07*a12);
  a19=(a19-a12);
  a12=2.9709464438211632e-08;
  a12=(a12*a22);
  a19=(a19+a12);
  if (res[0]!=0) res[0][33]=a19;
  a19=arg[16]? arg[16][0] : 0;
  a12=(a13*a15);
  a12=(a07*a12);
  a19=(a19-a12);
  if (res[0]!=0) res[0][34]=a19;
  a18=(a17*a18);
  a19=-2.9709464472005649e-08;
  a19=(a19*a08);
  a08=-9.9999999999160660e-01;
  a08=(a08*a23);
  a19=(a19+a08);
  a08=2.1960000700000012e-01;
  a08=(a08*a05);
  a19=(a19+a08);
  a08=2.1960000700000024e-01;
  a08=(a08*a01);
  a19=(a19+a08);
  a08=2.1960000700000004e-01;
  a08=(a08*a10);
  a19=(a19+a08);
  a18=(a18+a19);
  if (res[0]!=0) res[0][35]=a18;
  a18=arg[24]? arg[24][0] : 0;
  a19=casadi_sq(a00);
  a08=casadi_sq(a16);
  a19=(a19+a08);
  a19=(a14*a19);
  a18=(a18+a19);
  a19=9.9999999996642519e-01;
  a19=(a19*a21);
  a21=9.9999999998321198e-01;
  a21=(a21*a24);
  a19=(a19+a21);
  a21=9.9999999999999956e-01;
  a21=(a21*a22);
  a19=(a19+a21);
  a21=-4.3920001398894032e-01;
  a21=(a21*a23);
  a19=(a19+a21);
  a03=(a03*a26);
  a19=(a19+a03);
  a03=-2.2659287240095402e-03;
  a03=(a03*a05);
  a19=(a19+a03);
  a03=-2.2659287240079590e-03;
  a03=(a03*a01);
  a19=(a19+a03);
  a03=-2.2659287240095831e-03;
  a03=(a03*a10);
  a19=(a19+a03);
  a03=-5.0490091797600084e-02;
  a03=(a03*a14);
  a19=(a19+a03);
  a03=-5.0490091797600119e-02;
  a03=(a03*a17);
  a19=(a19+a03);
  a18=(a18+a19);
  if (res[0]!=0) res[0][36]=a18;
  a18=arg[17]? arg[17][0] : 0;
  a19=casadi_sq(a13);
  a03=casadi_sq(a15);
  a19=(a19+a03);
  a19=(a07*a19);
  a18=(a18+a19);
  a19=9.9999999996642530e-01;
  a19=(a19*a22);
  a03=-9.9999999999999967e-01;
  a21=arg[14]? arg[14][0] : 0;
  a24=casadi_sq(a13);
  a04=casadi_sq(a04);
  a24=(a24+a04);
  a24=(a07*a24);
  a21=(a21+a24);
  a03=(a03*a21);
  a19=(a19+a03);
  a18=(a18+a19);
  if (res[0]!=0) res[0][37]=a18;
  a11=(a14*a11);
  a18=4.0972050441824861e-06;
  a16=(a14*a16);
  a18=(a18*a16);
  a11=(a11+a18);
  if (res[0]!=0) res[0][38]=a11;
  a20=(a17*a20);
  a11=2.9709464196432036e-08;
  a11=(a11*a23);
  a23=-1.0000000000083935e+00;
  a23=(a23*a16);
  a11=(a11+a23);
  a20=(a20+a11);
  if (res[0]!=0) res[0][39]=a20;
  a20=arg[9]? arg[9][0] : 0;
  a11=arg[0]? arg[0][0] : 0;
  a23=arg[2]? arg[2][0] : 0;
  a18=casadi_sq(a23);
  a19=arg[1]? arg[1][0] : 0;
  a03=casadi_sq(a19);
  a18=(a18+a03);
  a18=(a11*a18);
  a20=(a20+a18);
  a18=-9.9999999998175326e-01;
  a18=(a18*a22);
  a22=9.9999999999854028e-01;
  a22=(a22*a21);
  a18=(a18+a22);
  a22=-1.7999999999912274e-02;
  a13=(a07*a13);
  a22=(a22*a13);
  a18=(a18+a22);
  a22=8.0999878989536893e-05;
  a22=(a22*a05);
  a18=(a18+a22);
  a22=8.0999878989479986e-05;
  a22=(a22*a01);
  a18=(a18+a22);
  a22=8.0999878989570367e-05;
  a22=(a22*a10);
  a18=(a18+a22);
  a22=8.0999878989513813e-05;
  a22=(a22*a14);
  a18=(a18+a22);
  a22=8.0999878989560488e-05;
  a22=(a22*a17);
  a18=(a18+a22);
  a22=8.0999999999998364e-05;
  a22=(a22*a07);
  a18=(a18+a22);
  a20=(a20+a18);
  if (res[0]!=0) res[0][40]=a20;
  a15=(a07*a15);
  a20=4.0972050437345742e-06;
  a20=(a20*a26);
  a18=-9.2064198971898854e-07;
  a18=(a18*a05);
  a20=(a20+a18);
  a18=-9.2064198973995399e-07;
  a18=(a18*a01);
  a20=(a20+a18);
  a18=-9.2064198968963695e-07;
  a18=(a18*a10);
  a20=(a20+a18);
  a18=-9.2064198972737470e-07;
  a18=(a18*a14);
  a20=(a20+a18);
  a18=-9.2064198974834014e-07;
  a18=(a18*a17);
  a20=(a20+a18);
  a15=(a15+a20);
  if (res[0]!=0) res[0][41]=a15;
  a00=(a14*a00);
  a15=2.9709464548761462e-08;
  a15=(a15*a16);
  a16=1.0000000000083937e+00;
  a16=(a16*a26);
  a15=(a15+a16);
  a16=-2.2470000400188642e-01;
  a16=(a16*a05);
  a15=(a15+a16);
  a16=-2.2470000400188664e-01;
  a16=(a16*a01);
  a15=(a15+a16);
  a16=-2.2470000400188639e-01;
  a16=(a16*a10);
  a15=(a15+a16);
  a16=-2.2470000400188622e-01;
  a16=(a16*a14);
  a15=(a15+a16);
  a16=-2.2470000400188628e-01;
  a16=(a16*a17);
  a15=(a15+a16);
  a00=(a00+a15);
  if (res[0]!=0) res[0][42]=a00;
  a19=(a11*a19);
  a00=2.8765386423435575e-06;
  a00=(a00*a13);
  a19=(a19+a00);
  if (res[0]!=0) res[0][43]=a19;
  a11=(a11*a23);
  a23=2.9709464702380268e-08;
  a23=(a23*a26);
  a26=-9.9999999999513367e-01;
  a26=(a26*a13);
  a23=(a23+a26);
  a26=8.9999933242832161e-03;
  a26=(a26*a05);
  a23=(a23+a26);
  a26=8.9999933242832439e-03;
  a26=(a26*a01);
  a23=(a23+a26);
  a26=8.9999933242831415e-03;
  a26=(a26*a10);
  a23=(a23+a26);
  a26=8.9999933242831519e-03;
  a26=(a26*a14);
  a23=(a23+a26);
  a26=8.9999933242831762e-03;
  a26=(a26*a17);
  a23=(a23+a26);
  a26=9.0000000000000028e-03;
  a26=(a26*a07);
  a23=(a23+a26);
  a11=(a11+a23);
  if (res[0]!=0) res[0][44]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_release(int mem) {
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_incref(void) {
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int left_arm_params_to_X_base_n_in(void) { return 70;}

CASADI_SYMBOL_EXPORT casadi_int left_arm_params_to_X_base_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real left_arm_params_to_X_base_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* left_arm_params_to_X_base_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    case 9: return "i9";
    case 10: return "i10";
    case 11: return "i11";
    case 12: return "i12";
    case 13: return "i13";
    case 14: return "i14";
    case 15: return "i15";
    case 16: return "i16";
    case 17: return "i17";
    case 18: return "i18";
    case 19: return "i19";
    case 20: return "i20";
    case 21: return "i21";
    case 22: return "i22";
    case 23: return "i23";
    case 24: return "i24";
    case 25: return "i25";
    case 26: return "i26";
    case 27: return "i27";
    case 28: return "i28";
    case 29: return "i29";
    case 30: return "i30";
    case 31: return "i31";
    case 32: return "i32";
    case 33: return "i33";
    case 34: return "i34";
    case 35: return "i35";
    case 36: return "i36";
    case 37: return "i37";
    case 38: return "i38";
    case 39: return "i39";
    case 40: return "i40";
    case 41: return "i41";
    case 42: return "i42";
    case 43: return "i43";
    case 44: return "i44";
    case 45: return "i45";
    case 46: return "i46";
    case 47: return "i47";
    case 48: return "i48";
    case 49: return "i49";
    case 50: return "i50";
    case 51: return "i51";
    case 52: return "i52";
    case 53: return "i53";
    case 54: return "i54";
    case 55: return "i55";
    case 56: return "i56";
    case 57: return "i57";
    case 58: return "i58";
    case 59: return "i59";
    case 60: return "i60";
    case 61: return "i61";
    case 62: return "i62";
    case 63: return "i63";
    case 64: return "i64";
    case 65: return "i65";
    case 66: return "i66";
    case 67: return "i67";
    case 68: return "i68";
    case 69: return "i69";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* left_arm_params_to_X_base_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* left_arm_params_to_X_base_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    case 17: return casadi_s0;
    case 18: return casadi_s0;
    case 19: return casadi_s0;
    case 20: return casadi_s0;
    case 21: return casadi_s0;
    case 22: return casadi_s0;
    case 23: return casadi_s0;
    case 24: return casadi_s0;
    case 25: return casadi_s0;
    case 26: return casadi_s0;
    case 27: return casadi_s0;
    case 28: return casadi_s0;
    case 29: return casadi_s0;
    case 30: return casadi_s0;
    case 31: return casadi_s0;
    case 32: return casadi_s0;
    case 33: return casadi_s0;
    case 34: return casadi_s0;
    case 35: return casadi_s0;
    case 36: return casadi_s0;
    case 37: return casadi_s0;
    case 38: return casadi_s0;
    case 39: return casadi_s0;
    case 40: return casadi_s0;
    case 41: return casadi_s0;
    case 42: return casadi_s0;
    case 43: return casadi_s0;
    case 44: return casadi_s0;
    case 45: return casadi_s0;
    case 46: return casadi_s0;
    case 47: return casadi_s0;
    case 48: return casadi_s0;
    case 49: return casadi_s0;
    case 50: return casadi_s0;
    case 51: return casadi_s0;
    case 52: return casadi_s0;
    case 53: return casadi_s0;
    case 54: return casadi_s0;
    case 55: return casadi_s0;
    case 56: return casadi_s0;
    case 57: return casadi_s0;
    case 58: return casadi_s0;
    case 59: return casadi_s0;
    case 60: return casadi_s0;
    case 61: return casadi_s0;
    case 62: return casadi_s0;
    case 63: return casadi_s0;
    case 64: return casadi_s0;
    case 65: return casadi_s0;
    case 66: return casadi_s0;
    case 67: return casadi_s0;
    case 68: return casadi_s0;
    case 69: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* left_arm_params_to_X_base_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
