/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int left_arm_params_to_X(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int left_arm_params_to_X_alloc_mem(void);
int left_arm_params_to_X_init_mem(int mem);
void left_arm_params_to_X_free_mem(int mem);
int left_arm_params_to_X_checkout(void);
void left_arm_params_to_X_release(int mem);
void left_arm_params_to_X_incref(void);
void left_arm_params_to_X_decref(void);
casadi_int left_arm_params_to_X_n_in(void);
casadi_int left_arm_params_to_X_n_out(void);
casadi_real left_arm_params_to_X_default_in(casadi_int i);
const char* left_arm_params_to_X_name_in(casadi_int i);
const char* left_arm_params_to_X_name_out(casadi_int i);
const casadi_int* left_arm_params_to_X_sparsity_in(casadi_int i);
const casadi_int* left_arm_params_to_X_sparsity_out(casadi_int i);
int left_arm_params_to_X_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int left_arm_params_to_X_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define left_arm_params_to_X_SZ_ARG 70
#define left_arm_params_to_X_SZ_RES 1
#define left_arm_params_to_X_SZ_IW 0
#define left_arm_params_to_X_SZ_W 0
#ifdef __cplusplus
} /* extern "C" */
#endif
