/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) left_arm_params_to_X_base_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {45, 1, 1};

/* left_arm_params_to_X_base:(i0,i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24,i25,i26,i27,i28,i29,i30,i31,i32,i33,i34,i35,i36,i37,i38,i39,i40,i41,i42,i43,i44,i45,i46,i47,i48,i49,i50,i51,i52,i53,i54,i55,i56,i57,i58,i59,i60,i61,i62,i63,i64,i65,i66,i67,i68,i69)->(o0[45]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=arg[68]? arg[68][0] : 0;
  a01=arg[60]? arg[60][0] : 0;
  a02=arg[63]? arg[63][0] : 0;
  a03=arg[62]? arg[62][0] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a00=(a00-a04);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[66]? arg[66][0] : 0;
  a04=arg[61]? arg[61][0] : 0;
  a05=(a02*a04);
  a05=(a01*a05);
  a00=(a00-a05);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[65]? arg[65][0] : 0;
  a05=(a03*a04);
  a05=(a01*a05);
  a00=(a00-a05);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[55]? arg[55][0] : 0;
  a05=arg[50]? arg[50][0] : 0;
  a06=arg[52]? arg[52][0] : 0;
  a07=arg[51]? arg[51][0] : 0;
  a08=(a06*a07);
  a08=(a05*a08);
  a00=(a00-a08);
  a08=-3.9858060582175702e-03;
  a09=arg[67]? arg[67][0] : 0;
  a10=casadi_sq(a02);
  a11=casadi_sq(a04);
  a10=(a10+a11);
  a10=(a01*a10);
  a09=(a09+a10);
  a08=(a08*a09);
  a10=1.0065031390097770e-02;
  a11=(a01*a02);
  a10=(a10*a11);
  a08=(a08+a10);
  a10=5.5625645698759214e-06;
  a10=(a10*a01);
  a08=(a08+a10);
  a00=(a00+a08);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[64]? arg[64][0] : 0;
  a02=casadi_sq(a02);
  a08=casadi_sq(a03);
  a02=(a02+a08);
  a02=(a01*a02);
  a00=(a00+a02);
  a00=(a00-a09);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[56]? arg[56][0] : 0;
  a02=arg[53]? arg[53][0] : 0;
  a08=(a02*a07);
  a08=(a05*a08);
  a00=(a00-a08);
  a08=-1.6405497421524548e-03;
  a08=(a08*a09);
  a10=-9.0647184030053951e-07;
  a10=(a10*a11);
  a08=(a08+a10);
  a00=(a00+a08);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[48]? arg[48][0] : 0;
  a08=arg[40]? arg[40][0] : 0;
  a10=arg[43]? arg[43][0] : 0;
  a12=arg[42]? arg[42][0] : 0;
  a13=(a10*a12);
  a13=(a08*a13);
  a00=(a00-a13);
  a13=7.9970102317807833e-06;
  a14=arg[54]? arg[54][0] : 0;
  a15=casadi_sq(a02);
  a16=casadi_sq(a06);
  a15=(a15+a16);
  a15=(a05*a15);
  a14=(a14+a15);
  a13=(a13*a14);
  a15=9.7524031603096871e-07;
  a16=(a05*a02);
  a15=(a15*a16);
  a13=(a13+a15);
  a00=(a00+a13);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[57]? arg[57][0] : 0;
  a13=casadi_sq(a02);
  a15=casadi_sq(a07);
  a13=(a13+a15);
  a13=(a05*a13);
  a00=(a00+a13);
  a13=9.9996553465636584e-01;
  a13=(a13*a09);
  a15=-9.9999999999999978e-01;
  a17=(a15*a14);
  a13=(a13+a17);
  a17=1.1853160729572618e-03;
  a17=(a17*a11);
  a13=(a13+a17);
  a17=-1.0104578112725666e-04;
  a17=(a17*a01);
  a13=(a13+a17);
  a00=(a00+a13);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[58]? arg[58][0] : 0;
  a02=(a02*a06);
  a02=(a05*a02);
  a00=(a00-a02);
  a02=-6.5390345858876211e-06;
  a02=(a02*a09);
  a13=1.6516104515478207e-05;
  a13=(a13*a11);
  a02=(a02+a13);
  a00=(a00+a02);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[45]? arg[45][0] : 0;
  a02=arg[41]? arg[41][0] : 0;
  a13=(a12*a02);
  a13=(a08*a13);
  a00=(a00-a13);
  a13=-7.0608685576160628e-08;
  a13=(a13*a09);
  a17=-3.8005797630778688e-03;
  a17=(a17*a14);
  a13=(a13+a17);
  a17=-4.6332863947313573e-04;
  a17=(a17*a16);
  a13=(a13+a17);
  a17=-4.5511063464497109e-07;
  a17=(a17*a11);
  a13=(a13+a17);
  a17=-3.6636367448149397e-07;
  a17=(a17*a01);
  a13=(a13+a17);
  a17=1.8829179944346644e-08;
  a17=(a17*a05);
  a13=(a13+a17);
  a00=(a00+a13);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[38]? arg[38][0] : 0;
  a13=arg[30]? arg[30][0] : 0;
  a17=arg[33]? arg[33][0] : 0;
  a18=arg[32]? arg[32][0] : 0;
  a19=(a17*a18);
  a19=(a13*a19);
  a00=(a00-a19);
  a19=-8.6623023428193052e-07;
  a20=arg[44]? arg[44][0] : 0;
  a21=casadi_sq(a10);
  a22=casadi_sq(a12);
  a21=(a21+a22);
  a21=(a08*a21);
  a20=(a20+a21);
  a19=(a19*a20);
  a21=3.3776776751958318e-07;
  a22=arg[31]? arg[31][0] : 0;
  a23=(a13*a22);
  a21=(a21*a23);
  a19=(a19+a21);
  a21=7.4440849107772468e-08;
  a21=(a21*a01);
  a19=(a19+a21);
  a21=7.4440850769391283e-08;
  a21=(a21*a05);
  a19=(a19+a21);
  a21=7.4441036846354311e-08;
  a21=(a21*a08);
  a19=(a19+a21);
  a00=(a00+a19);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[69]? arg[69][0] : 0;
  a19=casadi_sq(a03);
  a21=casadi_sq(a04);
  a19=(a19+a21);
  a19=(a01*a19);
  a00=(a00+a19);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[46]? arg[46][0] : 0;
  a19=(a10*a02);
  a19=(a08*a19);
  a00=(a00-a19);
  a19=3.9091098792265280e-08;
  a19=(a19*a09);
  a21=2.1041156376889487e-03;
  a21=(a21*a14);
  a19=(a19+a21);
  a21=-8.5480521514626281e-08;
  a21=(a21*a16);
  a19=(a19+a21);
  a21=-1.6900303479513784e-07;
  a21=(a21*a11);
  a19=(a19+a21);
  a21=2.1325438723984607e-07;
  a21=(a21*a01);
  a19=(a19+a21);
  a00=(a00+a19);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[59]? arg[59][0] : 0;
  a19=casadi_sq(a06);
  a21=casadi_sq(a07);
  a19=(a19+a21);
  a19=(a05*a19);
  a00=(a00+a19);
  a19=9.9999730854654123e-01;
  a19=(a19*a09);
  a21=1.0248089264937477e-03;
  a21=(a21*a11);
  a19=(a19+a21);
  a21=1.0165637403525430e-04;
  a21=(a21*a01);
  a19=(a19+a21);
  a00=(a00+a19);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[35]? arg[35][0] : 0;
  a19=(a18*a22);
  a19=(a13*a19);
  a00=(a00-a19);
  a19=4.7801619869857550e-04;
  a19=(a19*a20);
  a21=-2.9174301466232188e-04;
  a21=(a21*a23);
  a19=(a19+a21);
  a21=-2.3218310869677155e-05;
  a21=(a21*a01);
  a19=(a19+a21);
  a21=-2.3218311783988306e-05;
  a21=(a21*a05);
  a19=(a19+a21);
  a21=-2.3218414471702721e-05;
  a21=(a21*a08);
  a19=(a19+a21);
  a00=(a00+a19);
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[25]? arg[25][0] : 0;
  a19=arg[20]? arg[20][0] : 0;
  a21=arg[22]? arg[22][0] : 0;
  a24=arg[21]? arg[21][0] : 0;
  a25=(a21*a24);
  a25=(a19*a25);
  a00=(a00-a25);
  a25=3.3501516782891917e-03;
  a26=arg[29]? arg[29][0] : 0;
  a27=casadi_sq(a21);
  a28=casadi_sq(a24);
  a27=(a27+a28);
  a27=(a19*a27);
  a26=(a26+a27);
  a25=(a25*a26);
  a27=-3.1700203388619478e-04;
  a28=(a19*a24);
  a27=(a27*a28);
  a25=(a25+a27);
  a00=(a00+a25);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[36]? arg[36][0] : 0;
  a25=(a17*a22);
  a25=(a13*a25);
  a00=(a00-a25);
  a25=3.4198623762736086e-08;
  a25=(a25*a14);
  a27=1.8121293675056572e-03;
  a27=(a27*a20);
  a25=(a25+a27);
  a27=-3.9937873229165753e-04;
  a27=(a27*a23);
  a25=(a25+a27);
  a27=-8.8019157311791738e-05;
  a27=(a27*a01);
  a25=(a25+a27);
  a27=-8.8019160777846913e-05;
  a27=(a27*a05);
  a25=(a25+a27);
  a27=-8.8019550060524363e-05;
  a27=(a27*a08);
  a25=(a25+a27);
  a00=(a00+a25);
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[47]? arg[47][0] : 0;
  a25=casadi_sq(a10);
  a27=casadi_sq(a02);
  a25=(a25+a27);
  a25=(a08*a25);
  a00=(a00+a25);
  a25=1.8577779574985022e-05;
  a25=(a25*a09);
  a27=9.9996668325555693e-01;
  a27=(a27*a14);
  a25=(a25+a27);
  a25=(a25-a20);
  a27=-8.4772324692464288e-05;
  a27=(a27*a16);
  a25=(a25+a27);
  a27=-8.0389973951326427e-05;
  a27=(a27*a11);
  a25=(a25+a27);
  a27=1.0113453070255633e-04;
  a27=(a27*a01);
  a25=(a25+a27);
  a27=-2.1317019075940844e-07;
  a27=(a27*a05);
  a25=(a25+a27);
  a00=(a00+a25);
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[28]? arg[28][0] : 0;
  a25=arg[23]? arg[23][0] : 0;
  a27=(a25*a21);
  a27=(a19*a27);
  a00=(a00-a27);
  a27=3.9848705173260580e-06;
  a27=(a27*a26);
  a29=-3.7777781973149904e-07;
  a29=(a29*a28);
  a27=(a27+a29);
  a00=(a00+a27);
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[39]? arg[39][0] : 0;
  a27=casadi_sq(a18);
  a29=casadi_sq(a22);
  a27=(a27+a29);
  a27=(a13*a27);
  a00=(a00+a27);
  a27=1.8872003334153986e-05;
  a27=(a27*a14);
  a29=9.9999671617562214e-01;
  a29=(a29*a20);
  a27=(a27+a29);
  a29=3.5230634394712729e-06;
  a29=(a29*a16);
  a27=(a27+a29);
  a29=-4.4078253811660129e-01;
  a29=(a29*a23);
  a27=(a27+a29);
  a29=-4.8572060002534501e-02;
  a29=(a29*a01);
  a27=(a27+a29);
  a29=-4.8572061915232355e-02;
  a29=(a29*a05);
  a27=(a27+a29);
  a29=-4.8572276735108888e-02;
  a29=(a29*a08);
  a27=(a27+a29);
  a00=(a00+a27);
  if (res[0]!=0) res[0][19]=a00;
  a03=(a01*a03);
  if (res[0]!=0) res[0][20]=a03;
  a04=(a01*a04);
  if (res[0]!=0) res[0][21]=a04;
  a06=(a05*a06);
  a04=3.9858430836803953e-03;
  a04=(a04*a11);
  a03=-1.0067327231259610e-02;
  a03=(a03*a01);
  a04=(a04+a03);
  a06=(a06+a04);
  if (res[0]!=0) res[0][22]=a06;
  a06=arg[26]? arg[26][0] : 0;
  a04=(a25*a24);
  a04=(a19*a04);
  a06=(a06-a04);
  a04=1.1894463819021820e-03;
  a04=(a04*a26);
  a03=-2.1139145250693240e-07;
  a03=(a03*a28);
  a04=(a04+a03);
  a06=(a06+a04);
  if (res[0]!=0) res[0][23]=a06;
  a06=arg[15]? arg[15][0] : 0;
  a04=arg[10]? arg[10][0] : 0;
  a03=arg[12]? arg[12][0] : 0;
  a00=arg[11]? arg[11][0] : 0;
  a27=(a03*a00);
  a27=(a04*a27);
  a06=(a06-a27);
  a27=1.8661437194153665e-03;
  a29=arg[19]? arg[19][0] : 0;
  a30=casadi_sq(a03);
  a31=casadi_sq(a00);
  a30=(a30+a31);
  a30=(a04*a30);
  a29=(a29+a30);
  a27=(a27*a29);
  a30=-2.4852072768793529e-05;
  a31=(a04*a00);
  a30=(a30*a31);
  a27=(a27+a30);
  a06=(a06+a27);
  if (res[0]!=0) res[0][24]=a06;
  a06=arg[49]? arg[49][0] : 0;
  a27=casadi_sq(a12);
  a30=casadi_sq(a02);
  a27=(a27+a30);
  a27=(a08*a27);
  a06=(a06+a27);
  a27=1.8578316293298763e-05;
  a27=(a27*a09);
  a09=9.9999557261382954e-01;
  a09=(a09*a14);
  a27=(a27+a09);
  a09=-7.7726174675130813e-05;
  a09=(a09*a16);
  a27=(a27+a09);
  a09=-8.0380732758639057e-05;
  a09=(a09*a11);
  a27=(a27+a09);
  a09=1.0156709983420363e-04;
  a09=(a09*a01);
  a27=(a27+a09);
  a09=2.1647097332096552e-07;
  a09=(a09*a05);
  a27=(a27+a09);
  a06=(a06+a27);
  if (res[0]!=0) res[0][25]=a06;
  a07=(a05*a07);
  a06=9.9999071075758206e-01;
  a06=(a06*a11);
  a27=5.5253638250711979e-04;
  a27=(a27*a01);
  a06=(a06+a27);
  a07=(a07+a06);
  if (res[0]!=0) res[0][26]=a07;
  a07=arg[37]? arg[37][0] : 0;
  a06=casadi_sq(a17);
  a22=casadi_sq(a22);
  a06=(a06+a22);
  a06=(a13*a06);
  a07=(a07+a06);
  a06=1.8872060994090914e-05;
  a06=(a06*a14);
  a14=9.9999977149971186e-01;
  a14=(a14*a20);
  a06=(a06+a14);
  a14=1.0000014147985741e+00;
  a14=(a14*a26);
  a06=(a06+a14);
  a14=3.5230742036854414e-06;
  a14=(a14*a16);
  a06=(a06+a14);
  a14=-4.4078235991909809e-01;
  a14=(a14*a23);
  a06=(a06+a14);
  a14=-3.5756970150451845e-04;
  a14=(a14*a28);
  a06=(a06+a14);
  a14=-4.8571987320278565e-02;
  a14=(a14*a01);
  a06=(a06+a14);
  a14=-4.8571989232982254e-02;
  a14=(a14*a05);
  a06=(a06+a14);
  a14=-4.8572204053515158e-02;
  a14=(a14*a08);
  a06=(a06+a14);
  a14=6.8150447180827590e-08;
  a14=(a14*a13);
  a06=(a06+a14);
  a07=(a07+a06);
  if (res[0]!=0) res[0][27]=a07;
  a07=arg[18]? arg[18][0] : 0;
  a06=arg[13]? arg[13][0] : 0;
  a14=(a06*a03);
  a14=(a04*a14);
  a07=(a07-a14);
  a14=5.9850126713070323e-07;
  a14=(a14*a29);
  a22=-1.4241390305958073e-07;
  a22=(a22*a31);
  a14=(a14+a22);
  a07=(a07+a14);
  if (res[0]!=0) res[0][28]=a07;
  a07=arg[34]? arg[34][0] : 0;
  a14=casadi_sq(a17);
  a22=casadi_sq(a18);
  a14=(a14+a22);
  a14=(a13*a14);
  a07=(a07+a14);
  a14=3.5123246675024536e-06;
  a14=(a14*a20);
  a20=1.0000014147985745e+00;
  a20=(a20*a26);
  a14=(a14+a20);
  a20=-1.7819750316851944e-07;
  a20=(a20*a23);
  a14=(a14+a20);
  a20=-3.5756970150450083e-04;
  a20=(a20*a28);
  a14=(a14+a20);
  a20=6.3620061880837866e-08;
  a20=(a20*a01);
  a14=(a14+a20);
  a20=6.3620055140031418e-08;
  a20=(a20*a05);
  a14=(a14+a20);
  a20=6.3619300622515627e-08;
  a20=(a20*a08);
  a14=(a14+a20);
  a20=6.8150447178734082e-08;
  a20=(a20*a13);
  a14=(a14+a20);
  a07=(a07+a14);
  if (res[0]!=0) res[0][29]=a07;
  a02=(a08*a02);
  a07=9.9999056392282737e-01;
  a07=(a07*a16);
  a14=1.6405495012604195e-03;
  a14=(a14*a11);
  a07=(a07+a14);
  a14=-4.0625008182685220e-05;
  a14=(a14*a01);
  a07=(a07+a14);
  a14=-4.0625008182673287e-05;
  a14=(a14*a05);
  a07=(a07+a14);
  a02=(a02+a07);
  if (res[0]!=0) res[0][30]=a02;
  a12=(a08*a12);
  a02=3.8006156259802332e-03;
  a02=(a02*a16);
  a07=6.2351569050607415e-06;
  a07=(a07*a11);
  a02=(a02+a07);
  a07=4.6348741301702569e-04;
  a07=(a07*a01);
  a02=(a02+a07);
  a07=4.6348741301705708e-04;
  a07=(a07*a05);
  a02=(a02+a07);
  a12=(a12+a02);
  if (res[0]!=0) res[0][31]=a12;
  a12=arg[16]? arg[16][0] : 0;
  a02=(a06*a00);
  a02=(a04*a02);
  a12=(a12-a02);
  a02=3.2071441063347784e-04;
  a02=(a02*a29);
  a07=-7.2043183161338447e-05;
  a07=(a07*a31);
  a02=(a02+a07);
  a12=(a12+a02);
  if (res[0]!=0) res[0][32]=a12;
  a12=arg[24]? arg[24][0] : 0;
  a02=casadi_sq(a25);
  a07=casadi_sq(a21);
  a02=(a02+a07);
  a02=(a19*a02);
  a12=(a12+a02);
  a02=-1.2638440812533946e-05;
  a02=(a02*a26);
  a07=1.0000001028580909e+00;
  a07=(a07*a29);
  a02=(a02+a07);
  a07=2.1245633593289636e-06;
  a07=(a07*a28);
  a02=(a02+a07);
  a07=-4.4926703046099203e-01;
  a07=(a07*a31);
  a02=(a02+a07);
  a07=-5.0459954971492173e-02;
  a07=(a07*a01);
  a02=(a02+a07);
  a07=-5.0459954971492207e-02;
  a07=(a07*a05);
  a02=(a02+a07);
  a07=-5.0459954971491978e-02;
  a07=(a07*a08);
  a02=(a02+a07);
  a07=-5.0459954971492020e-02;
  a07=(a07*a13);
  a02=(a02+a07);
  a07=-5.0460055465068800e-02;
  a14=(a07*a19);
  a02=(a02+a14);
  a12=(a12+a02);
  if (res[0]!=0) res[0][33]=a12;
  a18=(a13*a18);
  a12=4.7801787765251643e-04;
  a12=(a12*a23);
  a02=-8.1041166467159148e-05;
  a02=(a02*a01);
  a12=(a12+a02);
  a02=-8.1041166467132422e-05;
  a02=(a02*a05);
  a12=(a12+a02);
  a02=-8.1041166467157413e-05;
  a02=(a02*a08);
  a12=(a12+a02);
  a18=(a18+a12);
  if (res[0]!=0) res[0][34]=a18;
  a18=arg[14]? arg[14][0] : 0;
  a12=casadi_sq(a06);
  a02=casadi_sq(a03);
  a12=(a12+a02);
  a12=(a04*a12);
  a18=(a18+a12);
  a12=9.9999303499098080e-01;
  a12=(a12*a29);
  a02=arg[17]? arg[17][0] : 0;
  a14=casadi_sq(a06);
  a00=casadi_sq(a00);
  a14=(a14+a00);
  a14=(a04*a14);
  a02=(a02+a14);
  a15=(a15*a02);
  a12=(a12+a15);
  a15=1.8551145007462635e-07;
  a15=(a15*a31);
  a12=(a12+a15);
  a18=(a18+a12);
  if (res[0]!=0) res[0][35]=a18;
  a10=(a08*a10);
  a18=-2.1041354924734171e-03;
  a18=(a18*a16);
  a16=-3.4519710059549529e-06;
  a16=(a16*a11);
  a18=(a18+a16);
  a16=-1.0000017561669596e+00;
  a16=(a16*a23);
  a18=(a18+a16);
  a16=-2.2039156700325774e-01;
  a16=(a16*a01);
  a18=(a18+a16);
  a16=-2.2039156700325763e-01;
  a16=(a16*a05);
  a18=(a18+a16);
  a16=-2.2039156700325746e-01;
  a16=(a16*a08);
  a18=(a18+a16);
  a10=(a10+a18);
  if (res[0]!=0) res[0][36]=a10;
  a10=arg[27]? arg[27][0] : 0;
  a18=casadi_sq(a25);
  a24=casadi_sq(a24);
  a18=(a18+a24);
  a18=(a19*a18);
  a10=(a10+a18);
  a18=-9.9999019115633692e-01;
  a18=(a18*a26);
  a26=1.0000001028580907e+00;
  a26=(a26*a29);
  a18=(a18+a26);
  a26=-2.1235515827263424e-06;
  a26=(a26*a28);
  a18=(a18+a26);
  a26=-4.4926703046099220e-01;
  a26=(a26*a31);
  a18=(a18+a26);
  a26=-5.0460155958838591e-02;
  a26=(a26*a01);
  a18=(a18+a26);
  a26=-5.0460155958838640e-02;
  a26=(a26*a05);
  a18=(a18+a26);
  a26=-5.0460155958838383e-02;
  a26=(a26*a08);
  a18=(a18+a26);
  a26=-5.0460155958838397e-02;
  a26=(a26*a13);
  a18=(a18+a26);
  a07=(a07*a19);
  a18=(a18+a07);
  a10=(a10+a18);
  if (res[0]!=0) res[0][37]=a10;
  a21=(a19*a21);
  a10=-3.3501892796154622e-03;
  a10=(a10*a28);
  a18=-3.1700914988071666e-04;
  a18=(a18*a01);
  a10=(a10+a18);
  a18=-3.1700914988070831e-04;
  a18=(a18*a05);
  a10=(a10+a18);
  a18=-3.1700914988068326e-04;
  a18=(a18*a08);
  a10=(a10+a18);
  a18=-3.1700914988072105e-04;
  a18=(a18*a13);
  a10=(a10+a18);
  a21=(a21+a10);
  if (res[0]!=0) res[0][38]=a21;
  a17=(a13*a17);
  a21=1.8121357323149922e-03;
  a21=(a21*a23);
  a23=-1.0000063192713642e+00;
  a23=(a23*a28);
  a21=(a21+a23);
  a23=2.1953297587554694e-04;
  a23=(a23*a01);
  a21=(a21+a23);
  a23=2.1953297587560158e-04;
  a23=(a23*a05);
  a21=(a21+a23);
  a23=2.1953297587559782e-04;
  a23=(a23*a08);
  a21=(a21+a23);
  a23=-1.7984575641609701e-04;
  a23=(a23*a13);
  a21=(a21+a23);
  a17=(a17+a21);
  if (res[0]!=0) res[0][39]=a17;
  a25=(a19*a25);
  a17=-1.1894597319722544e-03;
  a17=(a17*a28);
  a28=-1.0000017926859370e+00;
  a28=(a28*a31);
  a17=(a17+a28);
  a28=-2.2463337282975374e-01;
  a28=(a28*a01);
  a17=(a17+a28);
  a28=-2.2463337282975371e-01;
  a28=(a28*a05);
  a17=(a17+a28);
  a28=-2.2463337282975349e-01;
  a28=(a28*a08);
  a17=(a17+a28);
  a28=-2.2463337282975343e-01;
  a28=(a28*a13);
  a17=(a17+a28);
  a28=-2.2463315891182001e-01;
  a28=(a28*a19);
  a17=(a17+a28);
  a25=(a25+a17);
  if (res[0]!=0) res[0][40]=a25;
  a25=arg[9]? arg[9][0] : 0;
  a17=arg[0]? arg[0][0] : 0;
  a28=arg[2]? arg[2][0] : 0;
  a21=casadi_sq(a28);
  a23=arg[1]? arg[1][0] : 0;
  a10=casadi_sq(a23);
  a21=(a21+a10);
  a21=(a17*a21);
  a25=(a25+a21);
  a21=-9.9998285624624017e-01;
  a21=(a21*a29);
  a29=9.9998623584614021e-01;
  a29=(a29*a02);
  a21=(a21+a29);
  a29=4.8325286273151806e-06;
  a29=(a29*a31);
  a21=(a21+a29);
  a29=5.9627105429301388e-05;
  a29=(a29*a01);
  a21=(a21+a29);
  a29=-1.5213086203996916e-02;
  a06=(a04*a06);
  a29=(a29*a06);
  a21=(a21+a29);
  a29=5.9627105429399894e-05;
  a29=(a29*a05);
  a21=(a21+a29);
  a29=5.9627105429228861e-05;
  a29=(a29*a08);
  a21=(a21+a29);
  a29=5.9627105429207773e-05;
  a29=(a29*a13);
  a21=(a21+a29);
  a29=5.9627105429196850e-05;
  a29=(a29*a19);
  a21=(a21+a29);
  a29=5.8526533291243334e-05;
  a29=(a29*a04);
  a21=(a21+a29);
  a25=(a25+a21);
  if (res[0]!=0) res[0][41]=a25;
  a03=(a04*a03);
  a25=-1.8661502182918169e-03;
  a25=(a25*a31);
  a21=-2.4852245865065888e-05;
  a21=(a21*a01);
  a25=(a25+a21);
  a21=-2.4852245865005911e-05;
  a21=(a21*a05);
  a25=(a25+a21);
  a21=-2.4852245864916122e-05;
  a21=(a21*a08);
  a25=(a25+a21);
  a21=-2.4852245864852070e-05;
  a21=(a21*a13);
  a25=(a25+a21);
  a21=-2.4852245864863864e-05;
  a21=(a21*a19);
  a25=(a25+a21);
  a03=(a03+a25);
  if (res[0]!=0) res[0][42]=a03;
  a23=(a17*a23);
  a03=-3.2069920519409801e-04;
  a03=(a03*a31);
  a25=-7.6706423262422616e-03;
  a25=(a25*a01);
  a03=(a03+a25);
  a25=9.9994910650986901e-01;
  a25=(a25*a06);
  a03=(a03+a25);
  a25=-7.6706423262422538e-03;
  a21=(a25*a05);
  a03=(a03+a21);
  a25=(a25*a08);
  a03=(a03+a25);
  a25=-7.6706423262423639e-03;
  a25=(a25*a13);
  a03=(a03+a25);
  a25=-7.6706423262423787e-03;
  a25=(a25*a19);
  a03=(a03+a25);
  a25=-7.5986027798633799e-03;
  a25=(a25*a04);
  a03=(a03+a25);
  a23=(a23+a03);
  if (res[0]!=0) res[0][43]=a23;
  a17=(a17*a28);
  a28=3.0089242324748593e-06;
  a28=(a28*a31);
  a31=8.8823946973535899e-04;
  a31=(a31*a01);
  a28=(a28+a31);
  a31=-9.3819100537326852e-03;
  a31=(a31*a06);
  a28=(a28+a31);
  a31=8.8823946973536766e-04;
  a31=(a31*a05);
  a28=(a28+a31);
  a31=8.8823946973537709e-04;
  a31=(a31*a08);
  a28=(a28+a31);
  a31=8.8823946973532060e-04;
  a31=(a31*a13);
  a28=(a28+a31);
  a31=8.8823946973528450e-04;
  a31=(a31*a19);
  a28=(a28+a31);
  a31=8.8756356679172939e-04;
  a31=(a31*a04);
  a28=(a28+a31);
  a17=(a17+a28);
  if (res[0]!=0) res[0][44]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_release(int mem) {
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_incref(void) {
}

CASADI_SYMBOL_EXPORT void left_arm_params_to_X_base_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int left_arm_params_to_X_base_n_in(void) { return 70;}

CASADI_SYMBOL_EXPORT casadi_int left_arm_params_to_X_base_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real left_arm_params_to_X_base_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* left_arm_params_to_X_base_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    case 9: return "i9";
    case 10: return "i10";
    case 11: return "i11";
    case 12: return "i12";
    case 13: return "i13";
    case 14: return "i14";
    case 15: return "i15";
    case 16: return "i16";
    case 17: return "i17";
    case 18: return "i18";
    case 19: return "i19";
    case 20: return "i20";
    case 21: return "i21";
    case 22: return "i22";
    case 23: return "i23";
    case 24: return "i24";
    case 25: return "i25";
    case 26: return "i26";
    case 27: return "i27";
    case 28: return "i28";
    case 29: return "i29";
    case 30: return "i30";
    case 31: return "i31";
    case 32: return "i32";
    case 33: return "i33";
    case 34: return "i34";
    case 35: return "i35";
    case 36: return "i36";
    case 37: return "i37";
    case 38: return "i38";
    case 39: return "i39";
    case 40: return "i40";
    case 41: return "i41";
    case 42: return "i42";
    case 43: return "i43";
    case 44: return "i44";
    case 45: return "i45";
    case 46: return "i46";
    case 47: return "i47";
    case 48: return "i48";
    case 49: return "i49";
    case 50: return "i50";
    case 51: return "i51";
    case 52: return "i52";
    case 53: return "i53";
    case 54: return "i54";
    case 55: return "i55";
    case 56: return "i56";
    case 57: return "i57";
    case 58: return "i58";
    case 59: return "i59";
    case 60: return "i60";
    case 61: return "i61";
    case 62: return "i62";
    case 63: return "i63";
    case 64: return "i64";
    case 65: return "i65";
    case 66: return "i66";
    case 67: return "i67";
    case 68: return "i68";
    case 69: return "i69";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* left_arm_params_to_X_base_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* left_arm_params_to_X_base_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    case 6: return casadi_s0;
    case 7: return casadi_s0;
    case 8: return casadi_s0;
    case 9: return casadi_s0;
    case 10: return casadi_s0;
    case 11: return casadi_s0;
    case 12: return casadi_s0;
    case 13: return casadi_s0;
    case 14: return casadi_s0;
    case 15: return casadi_s0;
    case 16: return casadi_s0;
    case 17: return casadi_s0;
    case 18: return casadi_s0;
    case 19: return casadi_s0;
    case 20: return casadi_s0;
    case 21: return casadi_s0;
    case 22: return casadi_s0;
    case 23: return casadi_s0;
    case 24: return casadi_s0;
    case 25: return casadi_s0;
    case 26: return casadi_s0;
    case 27: return casadi_s0;
    case 28: return casadi_s0;
    case 29: return casadi_s0;
    case 30: return casadi_s0;
    case 31: return casadi_s0;
    case 32: return casadi_s0;
    case 33: return casadi_s0;
    case 34: return casadi_s0;
    case 35: return casadi_s0;
    case 36: return casadi_s0;
    case 37: return casadi_s0;
    case 38: return casadi_s0;
    case 39: return casadi_s0;
    case 40: return casadi_s0;
    case 41: return casadi_s0;
    case 42: return casadi_s0;
    case 43: return casadi_s0;
    case 44: return casadi_s0;
    case 45: return casadi_s0;
    case 46: return casadi_s0;
    case 47: return casadi_s0;
    case 48: return casadi_s0;
    case 49: return casadi_s0;
    case 50: return casadi_s0;
    case 51: return casadi_s0;
    case 52: return casadi_s0;
    case 53: return casadi_s0;
    case 54: return casadi_s0;
    case 55: return casadi_s0;
    case 56: return casadi_s0;
    case 57: return casadi_s0;
    case 58: return casadi_s0;
    case 59: return casadi_s0;
    case 60: return casadi_s0;
    case 61: return casadi_s0;
    case 62: return casadi_s0;
    case 63: return casadi_s0;
    case 64: return casadi_s0;
    case 65: return casadi_s0;
    case 66: return casadi_s0;
    case 67: return casadi_s0;
    case 68: return casadi_s0;
    case 69: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* left_arm_params_to_X_base_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int left_arm_params_to_X_base_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 70*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
